// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as model$0 from "../internal/model/models.js";

export interface ConfigDocument {
    "schemaVersion": number;
    "survey": SurveyDocument;
    "execution": model$0.ExecutionPlan;
    "network": NetworkSettings;
    "answers": model$0.AnswerPlan;
    "reverseFill": model$0.ReverseFillPlan;
    "psychometrics": model$0.PsychometricPolicy;
}

export interface NetworkSettings {
    "randomProxyEnabled": boolean;
    "proxyMode"?: string;
    "fixedProxyAddress"?: string;
    "proxySource": string;
    "customProxyApi"?: string;
    "proxyAreaCode"?: string;
    "randomUaEnabled": boolean;
    "randomUaRatios"?: { [_ in string]?: number } | null;
}

export interface SurveyDocument {
    "url": string;
    "provider": string;
    "title": string;
    "definition": model$0.SurveyDefinition;
}
