import type { AppViewState } from '../types'

export function createBaseAppViewState(version = __APP_VERSION__): AppViewState {
  return {
    appTitle: 'SurveyController',
    appVersion: version,
    themeMode: 'system',
    currentPage: 'task',
    topNav: [
      { id: 'task', label: '任务', icon: 'home', section: 'top', selected: true },
    ],
    bottomNav: [
      { id: 'settings', label: '设置', icon: 'sliders', section: 'bottom' },
      { id: 'community', label: '社区', icon: 'chat', section: 'bottom' },
      { id: 'more', label: '更多', icon: 'grid', section: 'bottom' },
    ],
    dashboard: {
      surveyTitle: '未命名问卷',
      surveyUrl: '',
      targetCount: 1,
      threadCount: 1,
      randomIpEnabled: false,
      randomIpQuota: 0,
      randomIpQuotaLabel: '未同步',
      randomIpStatus: '未连接代理服务',
      randomIpStatusTone: '',
      proxySource: '默认',
      proxyRemainingQuota: '0',
      proxyTotalQuota: '0',
      proxyQuotaKnown: false,
      proxyUserId: 0,
      proxyUserKnown: false,
      proxyPoolRemainingIp: 0,
      proxyPoolRemainingKnown: false,
      proxyAvailable: 0,
      proxyInUse: 0,
      questionCount: 0,
      progressCurrent: 0,
      progressTarget: 1,
      progressPercent: 0,
      statusText: '等待配置',
      platformLabel: '问卷星',
      metrics: [],
      quickActions: [],
      runtimeHint: '随机 UA 未开启',
      proxyHint: '失败停止已开启',
      questionRows: [],
      sessionRows: [],
    },
    runtimeGroups: [],
    strategyRules: [],
    dimensionGroups: [],
    reverseFillPlan: [],
    logLines: [],
    communityItems: ['QQ 群交流', '问题反馈', '参与贡献', '开源许可'],
    aboutItems: [
      { label: '版本', value: version },
      { label: '前端栈', value: 'React + Radix UI + Wails v3' },
      { label: '桌面壳', value: 'Wails v3' },
    ],
    donateItems: [
      { label: '微信', value: '赞赏码' },
      { label: '支付宝', value: '收款码' },
    ],
    settingsGroups: [],
  }
}
