import type { ShellState } from '../types'

export const emptyShellState: ShellState = {
  appTitle: 'SurveyController',
  appVersion: 'test',
  themeMode: 'system',
  currentPage: 'dashboard',
  topNav: [
    { id: 'dashboard', label: '概览', icon: 'home', section: 'top', selected: true },
    { id: 'runtime', label: '运行参数', icon: 'settings', section: 'top' },
    { id: 'strategy', label: '题目策略', icon: 'flow', section: 'top' },
    { id: 'reverse-fill', label: '反填', icon: 'refresh', section: 'top' },
    { id: 'logs', label: '日志', icon: 'document', section: 'top' },
  ],
  bottomNav: [
    { id: 'community', label: '社区', icon: 'chat', section: 'bottom' },
    { id: 'settings', label: '设置', icon: 'sliders', section: 'bottom' },
    { id: 'more', label: '更多', icon: 'grid', section: 'bottom' },
  ],
  dashboard: {
    surveyTitle: '未命名问卷',
    surveyUrl: '',
    targetCount: 1,
    threadCount: 1,
    randomIpEnabled: false,
    randomIpQuota: 0,
    randomIpQuotaLabel: '未同步',
    randomIpStatus: '未连接代理服务',
    randomIpStatusTone: '',
    proxySource: '默认',
    proxyAvailable: 0,
    proxyInUse: 0,
    questionCount: 0,
    progressCurrent: 0,
    progressTarget: 1,
    progressPercent: 0,
    statusText: '等待配置',
    platformLabel: '问卷星',
    metrics: [],
    quickActions: [],
    runtimeHint: '随机 UA 未开启',
    proxyHint: '失败停止已开启',
    questionRows: [],
    sessionRows: [],
  },
  runtimeGroups: [],
  strategyRules: [],
  dimensionGroups: [],
  reverseFillPlan: [],
  logLines: [],
  communityItems: [],
  aboutItems: [
    { label: '版本', value: 'test' },
    { label: '前端栈', value: 'React + Radix UI + Wails v3' },
    { label: '桌面壳', value: 'Wails v3' },
  ],
  donateItems: [
    { label: '微信', value: '赞赏码' },
    { label: '支付宝', value: '收款码' },
  ],
  settingsGroups: [],
}
