// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as time$0 from "../../../../time/models.js";

export class Event {
    /**
     * Creates a new Event instance.
     * @param {Partial<Event>} [$$source = {}] - The source object to create the Event.
     */
    constructor($$source = {}) {
        if (!("worker" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["worker"] = "";
        }
        if (!("message" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["message"] = "";
        }
        if (!("success" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["success"] = false;
        }
        if (!("fail" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["fail"] = false;
        }
        if (!("current" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["current"] = 0;
        }
        if (!("total" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["total"] = 0;
        }
        if (!("time" in $$source)) {
            /**
             * @member
             * @type {time$0.Time}
             */
            this["time"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Event instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Event}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Event(/** @type {Partial<Event>} */($$parsedSource));
    }
}

export class QuestionEntry {
    /**
     * Creates a new QuestionEntry instance.
     * @param {Partial<QuestionEntry>} [$$source = {}] - The source object to create the QuestionEntry.
     */
    constructor($$source = {}) {
        if (!("question_type" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["question_type"] = "";
        }
        if (!("probabilities" in $$source)) {
            /**
             * @member
             * @type {any}
             */
            this["probabilities"] = null;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string[] | undefined}
             */
            this["texts"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | undefined}
             */
            this["rows"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | undefined}
             */
            this["option_count"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["distribution_mode"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {any | undefined}
             */
            this["custom_weights"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | null | undefined}
             */
            this["question_num"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | null | undefined}
             */
            this["question_title"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["survey_provider"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | null | undefined}
             */
            this["provider_question_id"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | null | undefined}
             */
            this["provider_page_id"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {boolean | undefined}
             */
            this["ai_enabled"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {(string | null)[] | undefined}
             */
            this["option_fill_texts"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number[] | undefined}
             */
            this["fillable_option_indices"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {{ [_ in string]?: any }[] | undefined}
             */
            this["attached_option_selects"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {boolean | undefined}
             */
            this["is_location"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string[] | undefined}
             */
            this["location_parts"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string[] | undefined}
             */
            this["multi_text_blank_modes"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {boolean[] | undefined}
             */
            this["multi_text_blank_ai_flags"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number[][] | undefined}
             */
            this["multi_text_blank_int_ranges"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["text_random_mode"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number[] | undefined}
             */
            this["text_random_int_range"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["dimension"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["psycho_bias"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new QuestionEntry instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {QuestionEntry}
     */
    static createFrom($$source = {}) {
        const $$createField2_0 = $$createType0;
        const $$createField13_0 = $$createType1;
        const $$createField14_0 = $$createType2;
        const $$createField15_0 = $$createType4;
        const $$createField17_0 = $$createType0;
        const $$createField18_0 = $$createType0;
        const $$createField19_0 = $$createType5;
        const $$createField20_0 = $$createType6;
        const $$createField22_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("texts" in $$parsedSource) {
            $$parsedSource["texts"] = $$createField2_0($$parsedSource["texts"]);
        }
        if ("option_fill_texts" in $$parsedSource) {
            $$parsedSource["option_fill_texts"] = $$createField13_0($$parsedSource["option_fill_texts"]);
        }
        if ("fillable_option_indices" in $$parsedSource) {
            $$parsedSource["fillable_option_indices"] = $$createField14_0($$parsedSource["fillable_option_indices"]);
        }
        if ("attached_option_selects" in $$parsedSource) {
            $$parsedSource["attached_option_selects"] = $$createField15_0($$parsedSource["attached_option_selects"]);
        }
        if ("location_parts" in $$parsedSource) {
            $$parsedSource["location_parts"] = $$createField17_0($$parsedSource["location_parts"]);
        }
        if ("multi_text_blank_modes" in $$parsedSource) {
            $$parsedSource["multi_text_blank_modes"] = $$createField18_0($$parsedSource["multi_text_blank_modes"]);
        }
        if ("multi_text_blank_ai_flags" in $$parsedSource) {
            $$parsedSource["multi_text_blank_ai_flags"] = $$createField19_0($$parsedSource["multi_text_blank_ai_flags"]);
        }
        if ("multi_text_blank_int_ranges" in $$parsedSource) {
            $$parsedSource["multi_text_blank_int_ranges"] = $$createField20_0($$parsedSource["multi_text_blank_int_ranges"]);
        }
        if ("text_random_int_range" in $$parsedSource) {
            $$parsedSource["text_random_int_range"] = $$createField22_0($$parsedSource["text_random_int_range"]);
        }
        return new QuestionEntry(/** @type {Partial<QuestionEntry>} */($$parsedSource));
    }
}

export class QuestionMeta {
    /**
     * Creates a new QuestionMeta instance.
     * @param {Partial<QuestionMeta>} [$$source = {}] - The source object to create the QuestionMeta.
     */
    constructor($$source = {}) {
        if (!("num" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["num"] = 0;
        }
        if (!("title" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["title"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | null | undefined}
             */
            this["display_num"] = undefined;
        }
        if (!("description" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["description"] = "";
        }
        if (!("type_code" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["type_code"] = "";
        }
        if (!("options" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["options"] = 0;
        }
        if (!("rows" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["rows"] = 0;
        }
        if (!("row_texts" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["row_texts"] = [];
        }
        if (!("page" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["page"] = 0;
        }
        if (!("option_texts" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["option_texts"] = [];
        }
        if (!("provider" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["provider"] = "";
        }
        if (!("provider_question_id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["provider_question_id"] = "";
        }
        if (!("provider_page_id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["provider_page_id"] = "";
        }
        if (!("provider_type" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["provider_type"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {any | undefined}
             */
            this["provider_page_raw"] = undefined;
        }
        if (!("required" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["required"] = false;
        }
        if (!("is_description" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["is_description"] = false;
        }
        if (!("is_location" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["is_location"] = false;
        }
        if (!("is_rating" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["is_rating"] = false;
        }
        if (!("rating_max" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["rating_max"] = 0;
        }
        if (!("text_inputs" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["text_inputs"] = 0;
        }
        if (!("text_input_labels" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["text_input_labels"] = [];
        }
        if (!("is_text_like" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["is_text_like"] = false;
        }
        if (!("is_multi_text" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["is_multi_text"] = false;
        }
        if (!("is_slider_matrix" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["is_slider_matrix"] = false;
        }
        if (!("logic_parse_status" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["logic_parse_status"] = "";
        }
        if (!("has_jump" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["has_jump"] = false;
        }
        if (!("jump_rules" in $$source)) {
            /**
             * @member
             * @type {{ [_ in string]?: any }[]}
             */
            this["jump_rules"] = [];
        }
        if (!("has_display_condition" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["has_display_condition"] = false;
        }
        if (!("display_conditions" in $$source)) {
            /**
             * @member
             * @type {{ [_ in string]?: any }[]}
             */
            this["display_conditions"] = [];
        }
        if (!("has_dependent_display_logic" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["has_dependent_display_logic"] = false;
        }
        if (!("controls_display_targets" in $$source)) {
            /**
             * @member
             * @type {{ [_ in string]?: any }[]}
             */
            this["controls_display_targets"] = [];
        }
        if (!("question_media" in $$source)) {
            /**
             * @member
             * @type {{ [_ in string]?: any }[]}
             */
            this["question_media"] = [];
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {any | undefined}
             */
            this["slider_min"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {any | undefined}
             */
            this["slider_max"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {any | undefined}
             */
            this["slider_step"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | null | undefined}
             */
            this["multi_min_limit"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | null | undefined}
             */
            this["multi_max_limit"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | null | undefined}
             */
            this["forced_option_index"] = undefined;
        }
        if (!("forced_option_text" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["forced_option_text"] = "";
        }
        if (!("forced_texts" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["forced_texts"] = [];
        }
        if (!("fillable_options" in $$source)) {
            /**
             * @member
             * @type {number[]}
             */
            this["fillable_options"] = [];
        }
        if (!("attached_option_selects" in $$source)) {
            /**
             * @member
             * @type {{ [_ in string]?: any }[]}
             */
            this["attached_option_selects"] = [];
        }
        if (!("has_attached_option_select" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["has_attached_option_select"] = false;
        }
        if (!("unsupported" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["unsupported"] = false;
        }
        if (!("unsupported_reason" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["unsupported_reason"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new QuestionMeta instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {QuestionMeta}
     */
    static createFrom($$source = {}) {
        const $$createField7_0 = $$createType0;
        const $$createField9_0 = $$createType0;
        const $$createField21_0 = $$createType0;
        const $$createField27_0 = $$createType4;
        const $$createField29_0 = $$createType4;
        const $$createField31_0 = $$createType4;
        const $$createField32_0 = $$createType4;
        const $$createField40_0 = $$createType0;
        const $$createField41_0 = $$createType2;
        const $$createField42_0 = $$createType4;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("row_texts" in $$parsedSource) {
            $$parsedSource["row_texts"] = $$createField7_0($$parsedSource["row_texts"]);
        }
        if ("option_texts" in $$parsedSource) {
            $$parsedSource["option_texts"] = $$createField9_0($$parsedSource["option_texts"]);
        }
        if ("text_input_labels" in $$parsedSource) {
            $$parsedSource["text_input_labels"] = $$createField21_0($$parsedSource["text_input_labels"]);
        }
        if ("jump_rules" in $$parsedSource) {
            $$parsedSource["jump_rules"] = $$createField27_0($$parsedSource["jump_rules"]);
        }
        if ("display_conditions" in $$parsedSource) {
            $$parsedSource["display_conditions"] = $$createField29_0($$parsedSource["display_conditions"]);
        }
        if ("controls_display_targets" in $$parsedSource) {
            $$parsedSource["controls_display_targets"] = $$createField31_0($$parsedSource["controls_display_targets"]);
        }
        if ("question_media" in $$parsedSource) {
            $$parsedSource["question_media"] = $$createField32_0($$parsedSource["question_media"]);
        }
        if ("forced_texts" in $$parsedSource) {
            $$parsedSource["forced_texts"] = $$createField40_0($$parsedSource["forced_texts"]);
        }
        if ("fillable_options" in $$parsedSource) {
            $$parsedSource["fillable_options"] = $$createField41_0($$parsedSource["fillable_options"]);
        }
        if ("attached_option_selects" in $$parsedSource) {
            $$parsedSource["attached_option_selects"] = $$createField42_0($$parsedSource["attached_option_selects"]);
        }
        return new QuestionMeta(/** @type {Partial<QuestionMeta>} */($$parsedSource));
    }
}

export class RunResult {
    /**
     * Creates a new RunResult instance.
     * @param {Partial<RunResult>} [$$source = {}] - The source object to create the RunResult.
     */
    constructor($$source = {}) {
        if (!("success" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["success"] = 0;
        }
        if (!("fail" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["fail"] = 0;
        }
        if (!("stopped" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["stopped"] = false;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {ThreadProgress[] | undefined}
             */
            this["thread_progress"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RunResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {RunResult}
     */
    static createFrom($$source = {}) {
        const $$createField3_0 = $$createType8;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("thread_progress" in $$parsedSource) {
            $$parsedSource["thread_progress"] = $$createField3_0($$parsedSource["thread_progress"]);
        }
        return new RunResult(/** @type {Partial<RunResult>} */($$parsedSource));
    }
}

export class RuntimeConfig {
    /**
     * Creates a new RuntimeConfig instance.
     * @param {Partial<RuntimeConfig>} [$$source = {}] - The source object to create the RuntimeConfig.
     */
    constructor($$source = {}) {
        if (!("url" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["url"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["survey_title"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["survey_provider"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | undefined}
             */
            this["target"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | undefined}
             */
            this["threads"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number[] | undefined}
             */
            this["submit_interval"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number[] | undefined}
             */
            this["answer_duration"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string[] | undefined}
             */
            this["answer_datetime_window"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {boolean | undefined}
             */
            this["random_ip_enabled"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["proxy_source"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["custom_proxy_api"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | null | undefined}
             */
            this["proxy_area_code"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {boolean | undefined}
             */
            this["random_ua_enabled"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {{ [_ in string]?: number } | undefined}
             */
            this["random_ua_ratios"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {boolean | undefined}
             */
            this["fail_stop_enabled"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {boolean | undefined}
             */
            this["pause_on_aliyun_captcha"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {boolean | undefined}
             */
            this["reliability_mode_enabled"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | undefined}
             */
            this["psycho_target_alpha"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["ai_mode"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["ai_provider"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["ai_api_key"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["ai_base_url"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["ai_api_protocol"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["ai_model"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["ai_system_prompt"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {boolean | undefined}
             */
            this["reverse_fill_enabled"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["reverse_fill_source_path"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["reverse_fill_format"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | undefined}
             */
            this["reverse_fill_start_row"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | undefined}
             */
            this["reverse_fill_threads"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {{ [_ in string]?: any }[] | undefined}
             */
            this["answer_rules"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string[] | undefined}
             */
            this["dimension_groups"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {QuestionEntry[] | undefined}
             */
            this["question_entries"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {QuestionMeta[] | undefined}
             */
            this["questions_info"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RuntimeConfig instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {RuntimeConfig}
     */
    static createFrom($$source = {}) {
        const $$createField13_0 = $$createType9;
        const $$createField30_0 = $$createType4;
        const $$createField31_0 = $$createType0;
        const $$createField32_0 = $$createType11;
        const $$createField33_0 = $$createType13;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("random_ua_ratios" in $$parsedSource) {
            $$parsedSource["random_ua_ratios"] = $$createField13_0($$parsedSource["random_ua_ratios"]);
        }
        if ("answer_rules" in $$parsedSource) {
            $$parsedSource["answer_rules"] = $$createField30_0($$parsedSource["answer_rules"]);
        }
        if ("dimension_groups" in $$parsedSource) {
            $$parsedSource["dimension_groups"] = $$createField31_0($$parsedSource["dimension_groups"]);
        }
        if ("question_entries" in $$parsedSource) {
            $$parsedSource["question_entries"] = $$createField32_0($$parsedSource["question_entries"]);
        }
        if ("questions_info" in $$parsedSource) {
            $$parsedSource["questions_info"] = $$createField33_0($$parsedSource["questions_info"]);
        }
        return new RuntimeConfig(/** @type {Partial<RuntimeConfig>} */($$parsedSource));
    }
}

export class SurveyDefinition {
    /**
     * Creates a new SurveyDefinition instance.
     * @param {Partial<SurveyDefinition>} [$$source = {}] - The source object to create the SurveyDefinition.
     */
    constructor($$source = {}) {
        if (!("provider" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["provider"] = "";
        }
        if (!("title" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["title"] = "";
        }
        if (!("questions" in $$source)) {
            /**
             * @member
             * @type {QuestionMeta[]}
             */
            this["questions"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SurveyDefinition instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {SurveyDefinition}
     */
    static createFrom($$source = {}) {
        const $$createField2_0 = $$createType13;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("questions" in $$parsedSource) {
            $$parsedSource["questions"] = $$createField2_0($$parsedSource["questions"]);
        }
        return new SurveyDefinition(/** @type {Partial<SurveyDefinition>} */($$parsedSource));
    }
}

export class ThreadProgress {
    /**
     * Creates a new ThreadProgress instance.
     * @param {Partial<ThreadProgress>} [$$source = {}] - The source object to create the ThreadProgress.
     */
    constructor($$source = {}) {
        if (!("thread_name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["thread_name"] = "";
        }
        if (!("thread_index" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["thread_index"] = 0;
        }
        if (!("success_count" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["success_count"] = 0;
        }
        if (!("fail_count" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["fail_count"] = 0;
        }
        if (!("step_current" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["step_current"] = 0;
        }
        if (!("step_total" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["step_total"] = 0;
        }
        if (!("status_text" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["status_text"] = "";
        }
        if (!("running" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["running"] = false;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {time$0.Time | undefined}
             */
            this["last_update"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ThreadProgress instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ThreadProgress}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ThreadProgress(/** @type {Partial<ThreadProgress>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
const $$createType1 = $Create.Array($Create.Any);
const $$createType2 = $Create.Array($Create.Any);
const $$createType3 = $Create.Map($Create.Any, $Create.Any);
const $$createType4 = $Create.Array($$createType3);
const $$createType5 = $Create.Array($Create.Any);
const $$createType6 = $Create.Array($$createType2);
const $$createType7 = ThreadProgress.createFrom;
const $$createType8 = $Create.Array($$createType7);
const $$createType9 = $Create.Map($Create.Any, $Create.Any);
const $$createType10 = QuestionEntry.createFrom;
const $$createType11 = $Create.Array($$createType10);
const $$createType12 = QuestionMeta.createFrom;
const $$createType13 = $Create.Array($$createType12);
