// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export interface AnswerPlan {
    "rules"?: ConsistencyRule[] | null;
    "dimensions"?: string[] | null;
    "questions"?: QuestionStrategy[] | null;
}

export interface AttachedOptionSelect {
    "option_index": number;
    "option_text": string;
    "select_texts": string[] | null;
}

export interface ConsistencyRule {
    "id"?: string;
    "condition_question_num": number;
    "condition_mode": string;
    "condition_option_indices": number[] | null;
    "condition_row_index"?: number | null;
    "target_question_num": number;
    "action_mode": string;
    "target_option_indices": number[] | null;
    "target_row_index"?: number | null;
}

export interface DisplayCondition {
    "condition_question_num": number;
    "condition_mode": string;
    "condition_option_indices": number[] | null;
    "condition_row_index"?: number | null;
}

export interface DisplayControl {
    "target_question_num": number;
    "condition_mode": string;
    "condition_option_indices": number[] | null;
    "condition_row_index"?: number | null;
}

export interface Event {
    "worker": string;
    "message": string;
    "success": boolean;
    "fail": boolean;
    "current": number;
    "total": number;
    "time": string;
}

export interface ExecutionPlan {
    "target": number;
    "threads": number;
    "submitInterval": number[];
    "answerDuration": number[];
    "answerDatetimeWindow"?: string[];
    "failStop": boolean;
    "pauseOnAliyunCaptcha": boolean;
}

export interface JumpRule {
    "option_index": number;
    "jumpto": number;
    "option_text"?: string | null;
    "terminates_survey"?: boolean;
}

export interface PsychometricPolicy {
    "enabled": boolean;
    "targetAlpha": number;
}

export enum QuestionKind {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    QuestionKindSingle = "single",
    QuestionKindMultiple = "multiple",
    QuestionKindDropdown = "dropdown",
    QuestionKindScale = "scale",
    QuestionKindMatrix = "matrix",
    QuestionKindOrder = "order",
    QuestionKindSlider = "slider",
    QuestionKindText = "text",
    QuestionKindMultiText = "multi_text",
};

export interface QuestionMedia {
    "kind": string;
    "scope": string;
    "index"?: number | null;
    "source_url": string;
    "label": string;
}

export interface QuestionMeta {
    "num": number;
    "title": string;
    "display_num"?: number | null;
    "description": string;
    "type_code": string;
    "options": number;
    "rows": number;
    "row_texts": string[] | null;
    "page": number;
    "option_texts": string[] | null;
    "provider": string;
    "provider_question_id": string;
    "provider_page_id": string;
    "provider_type": string;
    "required": boolean;
    "is_description": boolean;
    "is_location": boolean;
    "is_rating": boolean;
    "rating_max": number;
    "text_inputs": number;
    "text_input_labels": string[] | null;
    "is_text_like": boolean;
    "is_multi_text": boolean;
    "is_slider_matrix": boolean;
    "logic_parse_status": string;
    "has_jump": boolean;
    "jump_rules"?: JumpRule[] | null;
    "has_display_condition": boolean;
    "display_conditions"?: DisplayCondition[] | null;
    "has_dependent_display_logic": boolean;
    "controls_display_targets"?: DisplayControl[] | null;
    "slider_min"?: string;
    "slider_max"?: string;
    "slider_step"?: string;
    "question_media"?: QuestionMedia[] | null;
    "multi_min_limit"?: number | null;
    "multi_max_limit"?: number | null;
    "forced_option_index"?: number | null;
    "forced_option_text": string;
    "forced_texts": string[] | null;
    "fillable_options": number[] | null;
    "attached_option_selects"?: AttachedOptionSelect[] | null;
    "has_attached_option_select": boolean;
    "unsupported": boolean;
    "unsupported_reason": string;
}

export interface QuestionStrategy {
    "question_type": QuestionKind;
    "probabilities": WeightTable;
    "texts"?: string[] | null;
    "rows"?: number;
    "option_count"?: number;
    "distribution_mode"?: string;
    "custom_weights"?: WeightTable;
    "question_num"?: number | null;
    "question_title"?: string | null;
    "survey_provider"?: string;
    "provider_question_id"?: string | null;
    "provider_page_id"?: string | null;
    "ai_enabled"?: boolean;
    "option_fill_texts"?: (string | null)[] | null;
    "fillable_option_indices"?: number[] | null;
    "attached_option_selects"?: AttachedOptionSelect[] | null;
    "is_location"?: boolean;
    "location_parts"?: string[] | null;
    "multi_text_blank_modes"?: string[] | null;
    "multi_text_blank_ai_flags"?: boolean[] | null;
    "multi_text_blank_int_ranges"?: (number[] | null)[] | null;
    "text_random_mode"?: string;
    "text_random_int_range"?: number[] | null;
    "dimension"?: string;
    "psycho_bias"?: string;
}

export interface ReverseFillPlan {
    "enabled": boolean;
    "sourcePath"?: string;
    "format": string;
    "startRow": number;
    "threads": number;
}

export interface RunResult {
    "success": number;
    "fail": number;
    "stopped": boolean;
    "thread_progress"?: ThreadProgress[] | null;
}

export interface SurveyDefinition {
    "provider": string;
    "title": string;
    "questions": QuestionMeta[] | null;
}

export interface ThreadProgress {
    "thread_name": string;
    "thread_index": number;
    "success_count": number;
    "fail_count": number;
    "step_current": number;
    "step_total": number;
    "status_text": string;
    "running": boolean;
    "last_update"?: string;
}

export interface WeightTable {
    "options"?: number[] | null;
    "rows"?: (number[] | null)[] | null;
}
