// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as time$0 from "../../../../time/models.js";

export interface Event {
    "worker": string;
    "message": string;
    "success": boolean;
    "fail": boolean;
    "current": number;
    "total": number;
    "time": time$0.Time;
}

export interface QuestionEntry {
    "question_type": string;
    "probabilities": any;
    "texts"?: string[] | null;
    "rows"?: number;
    "option_count"?: number;
    "distribution_mode"?: string;
    "custom_weights"?: any;
    "question_num"?: number | null;
    "question_title"?: string | null;
    "survey_provider"?: string;
    "provider_question_id"?: string | null;
    "provider_page_id"?: string | null;
    "ai_enabled"?: boolean;
    "option_fill_texts"?: (string | null)[] | null;
    "fillable_option_indices"?: number[] | null;
    "attached_option_selects"?: ({ [_ in string]?: any } | null)[] | null;
    "is_location"?: boolean;
    "location_parts"?: string[] | null;
    "multi_text_blank_modes"?: string[] | null;
    "multi_text_blank_ai_flags"?: boolean[] | null;
    "multi_text_blank_int_ranges"?: (number[] | null)[] | null;
    "text_random_mode"?: string;
    "text_random_int_range"?: number[] | null;
    "dimension"?: string;
    "psycho_bias"?: string;
}

export interface QuestionMeta {
    "num": number;
    "title": string;
    "display_num"?: number | null;
    "description": string;
    "type_code": string;
    "options": number;
    "rows": number;
    "row_texts": string[] | null;
    "page": number;
    "option_texts": string[] | null;
    "provider": string;
    "provider_question_id": string;
    "provider_page_id": string;
    "provider_type": string;
    "provider_page_raw"?: any;
    "required": boolean;
    "is_description": boolean;
    "is_location": boolean;
    "is_rating": boolean;
    "rating_max": number;
    "text_inputs": number;
    "text_input_labels": string[] | null;
    "is_text_like": boolean;
    "is_multi_text": boolean;
    "is_slider_matrix": boolean;
    "logic_parse_status": string;
    "has_jump": boolean;
    "jump_rules": ({ [_ in string]?: any } | null)[] | null;
    "has_display_condition": boolean;
    "display_conditions": ({ [_ in string]?: any } | null)[] | null;
    "has_dependent_display_logic": boolean;
    "controls_display_targets": ({ [_ in string]?: any } | null)[] | null;
    "question_media": ({ [_ in string]?: any } | null)[] | null;
    "slider_min"?: any;
    "slider_max"?: any;
    "slider_step"?: any;
    "multi_min_limit"?: number | null;
    "multi_max_limit"?: number | null;
    "forced_option_index"?: number | null;
    "forced_option_text": string;
    "forced_texts": string[] | null;
    "fillable_options": number[] | null;
    "attached_option_selects": ({ [_ in string]?: any } | null)[] | null;
    "has_attached_option_select": boolean;
    "unsupported": boolean;
    "unsupported_reason": string;
}

export interface RunResult {
    "success": number;
    "fail": number;
    "stopped": boolean;
    "thread_progress"?: ThreadProgress[] | null;
}

export interface RuntimeConfig {
    "url": string;
    "survey_title"?: string;
    "survey_provider"?: string;
    "target"?: number;
    "threads"?: number;
    "submit_interval"?: number[];
    "answer_duration"?: number[];
    "answer_datetime_window"?: string[];
    "random_ip_enabled"?: boolean;
    "proxy_source"?: string;
    "custom_proxy_api"?: string;
    "proxy_area_code"?: string | null;
    "random_ua_enabled"?: boolean;
    "random_ua_ratios"?: { [_ in string]?: number } | null;
    "fail_stop_enabled"?: boolean;
    "pause_on_aliyun_captcha"?: boolean;
    "reliability_mode_enabled"?: boolean;
    "psycho_target_alpha"?: number;
    "ai_mode"?: string;
    "ai_provider"?: string;
    "ai_api_key"?: string;
    "ai_base_url"?: string;
    "ai_api_protocol"?: string;
    "ai_model"?: string;
    "ai_system_prompt"?: string;
    "reverse_fill_enabled"?: boolean;
    "reverse_fill_source_path"?: string;
    "reverse_fill_format"?: string;
    "reverse_fill_start_row"?: number;
    "reverse_fill_threads"?: number;
    "answer_rules"?: ({ [_ in string]?: any } | null)[] | null;
    "dimension_groups"?: string[] | null;
    "question_entries"?: QuestionEntry[] | null;
    "questions_info"?: QuestionMeta[] | null;
}

export interface SurveyDefinition {
    "provider": string;
    "title": string;
    "questions": QuestionMeta[] | null;
}

export interface ThreadProgress {
    "thread_name": string;
    "thread_index": number;
    "success_count": number;
    "fail_count": number;
    "step_current": number;
    "step_total": number;
    "status_text": string;
    "running": boolean;
    "last_update"?: time$0.Time;
}
