<?xml version="1.0" encoding="utf-8"?>
<Project ToolsVersion="Current" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <PropertyGroup>
    <NugetPackageDirectory>$(MSBuildThisFileDirectory)packages</NugetPackageDirectory>
    <BaseOutputPath>$(MSBuildThisFileDirectory)artifacts\bin\</BaseOutputPath>
    <BaseIntermediateOutputPath>$(MSBuildThisFileDirectory)artifacts\obj\</BaseIntermediateOutputPath>
  </PropertyGroup>
  <Import Project="$(MSBuildThisFileDirectory)HybridCRT.props" />
</Project>

