version: '3'

vars:
  APP_NAME: "SurveyController"
  BIN_DIR: "bin"
  PACKAGE_MANAGER: '{{.PACKAGE_MANAGER | default "npm"}}'
  VITE_PORT: '{{.WAILS_VITE_PORT | default 9245}}'

includes:
  common: ./build/Taskfile.yml
  windows: ./build/windows/Taskfile.yml

tasks:
  build:
    summary: Builds the Windows application
    cmds:
      - task: windows:build

  package:
    summary: Packages a Windows production build of the application
    cmds:
      - task: windows:package

  run:
    summary: Runs the Windows application
    cmds:
      - task: windows:run
