// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as model$0 from "./internal/model/models.js";

export const Event = model$0.Event;

/**
 * @typedef {model$0.Event} Event
 */

export const QuestionMeta = model$0.QuestionMeta;

/**
 * @typedef {model$0.QuestionMeta} QuestionMeta
 */

export const RunResult = model$0.RunResult;

/**
 * @typedef {model$0.RunResult} RunResult
 */

export const RuntimeConfig = model$0.RuntimeConfig;

/**
 * @typedef {model$0.RuntimeConfig} RuntimeConfig
 */

export const SurveyDefinition = model$0.SurveyDefinition;

/**
 * @typedef {model$0.SurveyDefinition} SurveyDefinition
 */
