// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as model$0 from "./internal/model/models.js";

export type Event = model$0.Event;

export type QuestionMeta = model$0.QuestionMeta;

export type RunResult = model$0.RunResult;

export type RuntimeConfig = model$0.RuntimeConfig;

export type SurveyDefinition = model$0.SurveyDefinition;
