// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class QuotaSnapshot {
    /**
     * Creates a new QuotaSnapshot instance.
     * @param {Partial<QuotaSnapshot>} [$$source = {}] - The source object to create the QuotaSnapshot.
     */
    constructor($$source = {}) {
        if (!("RemainingQuota" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["RemainingQuota"] = 0;
        }
        if (!("TotalQuota" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["TotalQuota"] = 0;
        }
        if (!("UsedQuota" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["UsedQuota"] = 0;
        }
        if (!("QuotaKnown" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["QuotaKnown"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new QuotaSnapshot instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {QuotaSnapshot}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new QuotaSnapshot(/** @type {Partial<QuotaSnapshot>} */($$parsedSource));
    }
}
