// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export interface QuotaSnapshot {
    "RemainingQuota": number;
    "TotalQuota": number;
    "UsedQuota": number;
    "QuotaKnown": boolean;
}
