// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class Answer {
    /**
     * Creates a new Answer instance.
     * @param {Partial<Answer>} [$$source = {}] - The source object to create the Answer.
     */
    constructor($$source = {}) {
        if (!("question_num" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["question_num"] = 0;
        }
        if (!("kind" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["kind"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | null | undefined}
             */
            this["choice_index"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["text_value"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string[] | undefined}
             */
            this["text_values"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number[] | undefined}
             */
            this["matrix_choice_indexes"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Answer instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Answer}
     */
    static createFrom($$source = {}) {
        const $$createField4_0 = $$createType0;
        const $$createField5_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("text_values" in $$parsedSource) {
            $$parsedSource["text_values"] = $$createField4_0($$parsedSource["text_values"]);
        }
        if ("matrix_choice_indexes" in $$parsedSource) {
            $$parsedSource["matrix_choice_indexes"] = $$createField5_0($$parsedSource["matrix_choice_indexes"]);
        }
        return new Answer(/** @type {Partial<Answer>} */($$parsedSource));
    }
}

export class Column {
    /**
     * Creates a new Column instance.
     * @param {Partial<Column>} [$$source = {}] - The source object to create the Column.
     */
    constructor($$source = {}) {
        if (!("column_index" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["column_index"] = 0;
        }
        if (!("header" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["header"] = "";
        }
        if (!("question_num" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["question_num"] = 0;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["suffix"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Column instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Column}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Column(/** @type {Partial<Column>} */($$parsedSource));
    }
}

export class Preview {
    /**
     * Creates a new Preview instance.
     * @param {Partial<Preview>} [$$source = {}] - The source object to create the Preview.
     */
    constructor($$source = {}) {
        if (!("source_path" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["source_path"] = "";
        }
        if (!("selected_format" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["selected_format"] = "";
        }
        if (!("detected_format" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["detected_format"] = "";
        }
        if (!("header_row_number" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["header_row_number"] = 0;
        }
        if (!("total_data_rows" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["total_data_rows"] = 0;
        }
        if (!("question_columns" in $$source)) {
            /**
             * @member
             * @type {{ [_ in `${number}`]?: Column[] }}
             */
            this["question_columns"] = {};
        }
        if (!("sample_rows" in $$source)) {
            /**
             * @member
             * @type {SampleRow[]}
             */
            this["sample_rows"] = [];
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string[] | undefined}
             */
            this["unsupported_fields"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Preview instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Preview}
     */
    static createFrom($$source = {}) {
        const $$createField5_0 = $$createType4;
        const $$createField6_0 = $$createType6;
        const $$createField7_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("question_columns" in $$parsedSource) {
            $$parsedSource["question_columns"] = $$createField5_0($$parsedSource["question_columns"]);
        }
        if ("sample_rows" in $$parsedSource) {
            $$parsedSource["sample_rows"] = $$createField6_0($$parsedSource["sample_rows"]);
        }
        if ("unsupported_fields" in $$parsedSource) {
            $$parsedSource["unsupported_fields"] = $$createField7_0($$parsedSource["unsupported_fields"]);
        }
        return new Preview(/** @type {Partial<Preview>} */($$parsedSource));
    }
}

export class SampleRow {
    /**
     * Creates a new SampleRow instance.
     * @param {Partial<SampleRow>} [$$source = {}] - The source object to create the SampleRow.
     */
    constructor($$source = {}) {
        if (!("data_row_number" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["data_row_number"] = 0;
        }
        if (!("worksheet_row_number" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["worksheet_row_number"] = 0;
        }
        if (!("answers" in $$source)) {
            /**
             * @member
             * @type {{ [_ in `${number}`]?: Answer }}
             */
            this["answers"] = {};
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SampleRow instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {SampleRow}
     */
    static createFrom($$source = {}) {
        const $$createField2_0 = $$createType8;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("answers" in $$parsedSource) {
            $$parsedSource["answers"] = $$createField2_0($$parsedSource["answers"]);
        }
        return new SampleRow(/** @type {Partial<SampleRow>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
const $$createType1 = $Create.Array($Create.Any);
const $$createType2 = Column.createFrom;
const $$createType3 = $Create.Array($$createType2);
const $$createType4 = $Create.Map($Create.Any, $$createType3);
const $$createType5 = SampleRow.createFrom;
const $$createType6 = $Create.Array($$createType5);
const $$createType7 = Answer.createFrom;
const $$createType8 = $Create.Map($Create.Any, $$createType7);
