// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as reversefill$0 from "../../../../../surveycontroller/surveycore/reversefill/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * @param {$models.ParseSurveyRequest} request
 * @returns {$CancellablePromise<$models.SurveyCoreState>}
 */
export function BuildDefaultConfig(request) {
    return $Call.ByID(1281628077, request).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * @returns {$CancellablePromise<$models.RunTaskState>}
 */
export function CancelRun() {
    return $Call.ByID(56584525).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * @returns {$CancellablePromise<$models.RandomIPBonusState>}
 */
export function ClaimRandomIPBonus() {
    return $Call.ByID(3791153487).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function ConfirmClose() {
    return $Call.ByID(4006498174);
}

/**
 * @param {$models.DecodeQRCodeRequest} request
 * @returns {$CancellablePromise<$models.QRCodeDecodeState>}
 */
export function DecodeQRCode(request) {
    return $Call.ByID(1524137838, request).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * @returns {$CancellablePromise<$models.AppSettings>}
 */
export function DismissStartupTutorialHint() {
    return $Call.ByID(580762776).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType4($result);
    }));
}

/**
 * @param {string} path
 * @param {string[]} lines
 * @returns {$CancellablePromise<string>}
 */
export function ExportLogLines(path, lines) {
    return $Call.ByID(572398321, path, lines);
}

/**
 * @returns {$CancellablePromise<$models.AppSettings>}
 */
export function GetAppSettings() {
    return $Call.ByID(120288048).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType4($result);
    }));
}

/**
 * @returns {$CancellablePromise<$models.ContactStatus>}
 */
export function GetContactStatus() {
    return $Call.ByID(4132353704).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType5($result);
    }));
}

/**
 * @returns {$CancellablePromise<$models.IPUsageSummary>}
 */
export function GetIPUsageSummary() {
    return $Call.ByID(1693062290).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType6($result);
    }));
}

/**
 * @param {string} source
 * @returns {$CancellablePromise<$models.ProxyAreaOptionsState>}
 */
export function GetProxyAreaOptions(source) {
    return $Call.ByID(3749919539, source).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType7($result);
    }));
}

/**
 * @returns {$CancellablePromise<$models.ProxyStatus>}
 */
export function GetProxyStatus() {
    return $Call.ByID(3425455756).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType8($result);
    }));
}

/**
 * @returns {$CancellablePromise<$models.RunTaskState>}
 */
export function GetRunTaskState() {
    return $Call.ByID(2123585291).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * @returns {$CancellablePromise<$models.ShellState>}
 */
export function GetShellState() {
    return $Call.ByID(4132789757).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType9($result);
    }));
}

/**
 * @returns {$CancellablePromise<$models.StartupTutorialHintState>}
 */
export function GetStartupTutorialHint() {
    return $Call.ByID(3040083232).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType10($result);
    }));
}

/**
 * @param {$models.LoadConfigRequest} request
 * @returns {$CancellablePromise<$models.ConfigFileState>}
 */
export function LoadConfig(request) {
    return $Call.ByID(1600851788, request).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType11($result);
    }));
}

/**
 * @returns {$CancellablePromise<$models.AppSettings>}
 */
export function MarkRandomIPBonusPlayed() {
    return $Call.ByID(3386304207).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType4($result);
    }));
}

/**
 * @param {$models.ParseSurveyRequest} request
 * @returns {$CancellablePromise<$models.SurveyCoreState>}
 */
export function ParseSurvey(request) {
    return $Call.ByID(2302332847, request).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * @param {string} reason
 * @returns {$CancellablePromise<$models.RunTaskState>}
 */
export function PauseRun(reason) {
    return $Call.ByID(2429326169, reason).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * @param {$models.ReverseFillPreviewRequest} request
 * @returns {$CancellablePromise<reversefill$0.Preview>}
 */
export function PreviewReverseFill(request) {
    return $Call.ByID(2827367849, request).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType12($result);
    }));
}

/**
 * @param {$models.RedeemProxyCardRequest} request
 * @returns {$CancellablePromise<$models.ProxyRedeemState>}
 */
export function RedeemProxyCard(request) {
    return $Call.ByID(1479022500, request).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType13($result);
    }));
}

/**
 * @returns {$CancellablePromise<$models.AppSettings>}
 */
export function ResetAppSettings() {
    return $Call.ByID(1440769833).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType4($result);
    }));
}

/**
 * @returns {$CancellablePromise<$models.RunTaskState>}
 */
export function ResumeRun() {
    return $Call.ByID(1615000490).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * @param {$models.RunSurveyRequest} request
 * @returns {$CancellablePromise<$models.SurveyCoreState>}
 */
export function RunSurvey(request) {
    return $Call.ByID(816852985, request).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * @param {$models.SaveSettingsRequest} request
 * @returns {$CancellablePromise<$models.AppSettings>}
 */
export function SaveAppSettings(request) {
    return $Call.ByID(236977175, request).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType4($result);
    }));
}

/**
 * @param {$models.SaveConfigRequest} request
 * @returns {$CancellablePromise<$models.ConfigFileState>}
 */
export function SaveConfig(request) {
    return $Call.ByID(2775748437, request).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType11($result);
    }));
}

/**
 * @returns {$CancellablePromise<boolean>}
 */
export function ShouldConfirmClose() {
    return $Call.ByID(3723452269);
}

/**
 * @param {$models.RunSurveyRequest} request
 * @returns {$CancellablePromise<$models.RunTaskState>}
 */
export function StartRun(request) {
    return $Call.ByID(1211922163, request).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * @param {$models.ContactRequest} request
 * @returns {$CancellablePromise<$models.ContactState>}
 */
export function SubmitContactMessage(request) {
    return $Call.ByID(3578130657, request).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType14($result);
    }));
}

/**
 * @param {string} source
 * @returns {$CancellablePromise<$models.ProxyStatus>}
 */
export function SyncProxyStatus(source) {
    return $Call.ByID(3841839841, source).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType8($result);
    }));
}

/**
 * @param {$models.TestAIConnectionRequest} request
 * @returns {$CancellablePromise<$models.AIConnectionTestState>}
 */
export function TestAIConnection(request) {
    return $Call.ByID(3649348096, request).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType15($result);
    }));
}

/**
 * @param {$models.TestCustomProxyAPIRequest} request
 * @returns {$CancellablePromise<$models.CustomProxyAPITestState>}
 */
export function TestCustomProxyAPI(request) {
    return $Call.ByID(3872558909, request).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType16($result);
    }));
}

// Private type creation functions
const $$createType0 = $models.SurveyCoreState.createFrom;
const $$createType1 = $models.RunTaskState.createFrom;
const $$createType2 = $models.RandomIPBonusState.createFrom;
const $$createType3 = $models.QRCodeDecodeState.createFrom;
const $$createType4 = $models.AppSettings.createFrom;
const $$createType5 = $models.ContactStatus.createFrom;
const $$createType6 = $models.IPUsageSummary.createFrom;
const $$createType7 = $models.ProxyAreaOptionsState.createFrom;
const $$createType8 = $models.ProxyStatus.createFrom;
const $$createType9 = $models.ShellState.createFrom;
const $$createType10 = $models.StartupTutorialHintState.createFrom;
const $$createType11 = $models.ConfigFileState.createFrom;
const $$createType12 = reversefill$0.Preview.createFrom;
const $$createType13 = $models.ProxyRedeemState.createFrom;
const $$createType14 = $models.ContactState.createFrom;
const $$createType15 = $models.AIConnectionTestState.createFrom;
const $$createType16 = $models.CustomProxyAPITestState.createFrom;
