// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as reversefill$0 from "../../../../../surveycontroller/surveycore/reversefill/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function BuildDefaultConfig(request: $models.ParseSurveyRequest): $CancellablePromise<$models.SurveyCoreState> {
    return $Call.ByID(1281628077, request);
}

export function CancelRun(): $CancellablePromise<$models.RunTaskState> {
    return $Call.ByID(56584525);
}

export function ConfirmClose(): $CancellablePromise<void> {
    return $Call.ByID(4006498174);
}

export function DecodeQRCode(request: $models.DecodeQRCodeRequest): $CancellablePromise<$models.QRCodeDecodeState> {
    return $Call.ByID(1524137838, request);
}

export function DismissStartupTutorialHint(): $CancellablePromise<$models.AppSettings> {
    return $Call.ByID(580762776);
}

export function ExportLogLines(path: string, lines: string[] | null): $CancellablePromise<string> {
    return $Call.ByID(572398321, path, lines);
}

export function GetAppSettings(): $CancellablePromise<$models.AppSettings> {
    return $Call.ByID(120288048);
}

export function GetProxyAreaOptions(source: string): $CancellablePromise<$models.ProxyAreaOptionsState> {
    return $Call.ByID(3749919539, source);
}

export function GetProxyStatus(): $CancellablePromise<$models.ProxyStatus> {
    return $Call.ByID(3425455756);
}

export function GetRunTaskState(): $CancellablePromise<$models.RunTaskState> {
    return $Call.ByID(2123585291);
}

export function GetShellState(): $CancellablePromise<$models.ShellState> {
    return $Call.ByID(4132789757);
}

export function GetStartupTutorialHint(): $CancellablePromise<$models.StartupTutorialHintState> {
    return $Call.ByID(3040083232);
}

export function LoadConfig(request: $models.LoadConfigRequest): $CancellablePromise<$models.ConfigFileState> {
    return $Call.ByID(1600851788, request);
}

export function ParseSurvey(request: $models.ParseSurveyRequest): $CancellablePromise<$models.SurveyCoreState> {
    return $Call.ByID(2302332847, request);
}

export function PauseRun(reason: string): $CancellablePromise<$models.RunTaskState> {
    return $Call.ByID(2429326169, reason);
}

export function PreviewReverseFill(request: $models.ReverseFillPreviewRequest): $CancellablePromise<reversefill$0.Preview> {
    return $Call.ByID(2827367849, request);
}

export function RedeemProxyCard(request: $models.RedeemProxyCardRequest): $CancellablePromise<$models.ProxyRedeemState> {
    return $Call.ByID(1479022500, request);
}

export function ResetAppSettings(): $CancellablePromise<$models.AppSettings> {
    return $Call.ByID(1440769833);
}

export function ResumeRun(): $CancellablePromise<$models.RunTaskState> {
    return $Call.ByID(1615000490);
}

export function RunSurvey(request: $models.RunSurveyRequest): $CancellablePromise<$models.SurveyCoreState> {
    return $Call.ByID(816852985, request);
}

export function SaveAppSettings(request: $models.SaveSettingsRequest): $CancellablePromise<$models.AppSettings> {
    return $Call.ByID(236977175, request);
}

export function SaveConfig(request: $models.SaveConfigRequest): $CancellablePromise<$models.ConfigFileState> {
    return $Call.ByID(2775748437, request);
}

export function ShouldConfirmClose(): $CancellablePromise<boolean> {
    return $Call.ByID(3723452269);
}

export function StartRun(request: $models.RunSurveyRequest): $CancellablePromise<$models.RunTaskState> {
    return $Call.ByID(1211922163, request);
}

export function SyncProxyStatus(source: string): $CancellablePromise<$models.ProxyStatus> {
    return $Call.ByID(3841839841, source);
}

export function TestAIConnection(request: $models.TestAIConnectionRequest): $CancellablePromise<$models.AIConnectionTestState> {
    return $Call.ByID(3649348096, request);
}

export function TestCustomProxyAPI(request: $models.TestCustomProxyAPIRequest): $CancellablePromise<$models.CustomProxyAPITestState> {
    return $Call.ByID(3872558909, request);
}
