// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as proxycore$0 from "../../../../../surveycontroller/proxycore/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as surveycore$0 from "../../../../../surveycontroller/surveycore/models.js";

export interface AIConnectionTestState {
    "success": boolean;
    "message": string;
}

export interface AppSettings {
    "configDirectory": string;
    "themeMode": string;
    "showNavigationText": boolean;
    "micaEnabled": boolean;
    "topmost": boolean;
    "askSaveOnClose": boolean;
    "preventSleepDuringRun": boolean;
    "taskResultNotification": boolean;
    "submissionReportTelemetry": boolean;
    "setupWizardVersion": number;
    "autoCheckUpdate": boolean;
    "autoSaveLogs": boolean;
    "notifications": boolean;
    "autosaveLogCount": number;
    "runtimeDefaults"?: { [_ in string]?: string } | null;
}

export interface ConfigFileState {
    "path": string;
    "exists": boolean;
    "config"?: surveycore$0.RuntimeConfig | null;
}

export interface CustomProxyAPITestState {
    "success": boolean;
    "message": string;
    "proxies": string[] | null;
}

export interface DashboardState {
    "surveyTitle": string;
    "surveyUrl": string;
    "targetCount": number;
    "threadCount": number;
    "randomIpEnabled": boolean;
    "randomIpQuota": number;
    "randomIpQuotaLabel": string;
    "randomIpStatus": string;
    "randomIpStatusTone": string;
    "proxySource": string;
    "questionCount": number;
    "progressCurrent": number;
    "progressTarget": number;
    "progressPercent": number;
    "statusText": string;
    "platformLabel": string;
    "metrics": PageMetric[] | null;
    "quickActions": QuickAction[] | null;
    "questionRows": QuestionRow[] | null;
    "sessionRows": SessionRow[] | null;
}

export interface DecodeQRCodeRequest {
    "path": string;
    "dataUrl"?: string;
    "name"?: string;
}

export interface LoadConfigRequest {
    "path": string;
}

export interface NavItem {
    "id": string;
    "label": string;
    "icon": string;
    "section": string;
    "badge"?: string;
    "selected"?: boolean;
}

export interface PageMetric {
    "label": string;
    "value": string;
    "tone"?: string;
}

export interface ParseSurveyRequest {
    "url": string;
}

export interface ProxyAreaCity {
    "code": string;
    "name": string;
}

export interface ProxyAreaOptionsState {
    "source": string;
    "hasAll": boolean;
    "provinces": ProxyAreaProvince[] | null;
}

export interface ProxyAreaProvince {
    "code": string;
    "name": string;
    "cities": ProxyAreaCity[] | null;
}

export interface ProxyRedeemState {
    "redeemed": boolean;
    "cardQuota": number;
    "cardQuotaLabel": string;
    "detail"?: string;
    "status": ProxyStatus;
}

export interface ProxyStatus {
    "available": number;
    "inUse": number;
    "userId": number;
    "userKnown": boolean;
    "poolRemainingIp": number;
    "poolRemainingKnown": boolean;
    "remainingQuota": string;
    "totalQuota": string;
    "quotaKnown": boolean;
    "randomIpEnabled": boolean;
    "source": string;
    "message": string;
    "quota": proxycore$0.QuotaSnapshot;
}

export interface QRCodeDecodeState {
    "path": string;
    "text": string;
}

export interface QuestionRow {
    "index": number;
    "type": string;
    "dimension": string;
    "strategy": string;
}

export interface QuickAction {
    "id": string;
    "label": string;
    "icon": string;
    "emphasis"?: string;
}

export interface RedeemProxyCardRequest {
    "cardCode": string;
    "source"?: string;
}

export interface ReverseFillPreviewRequest {
    "path": string;
    "format": string;
    "startRow": number;
    "questions": surveycore$0.QuestionMeta[] | null;
}

export interface ReverseFillRow {
    "question": string;
    "column": string;
    "state": string;
}

export interface RunSurveyRequest {
    "config": surveycore$0.RuntimeConfig;
}

export interface RunTaskState {
    "running": boolean;
    "canceling": boolean;
    "paused": boolean;
    "pauseReason"?: string;
    "result"?: surveycore$0.RunResult | null;
    "events"?: surveycore$0.Event[] | null;
    "error"?: string;
    "startedAt"?: string;
    "endedAt"?: string;
    "config"?: surveycore$0.RuntimeConfig | null;
}

export interface SaveConfigRequest {
    "path": string;
    "config": surveycore$0.RuntimeConfig;
}

export interface SaveSettingsRequest {
    "settings": AppSettings;
}

export interface SessionRow {
    "thread": string;
    "status": string;
    "progress": number;
}

export interface SettingField {
    "id": string;
    "label": string;
    "description": string;
    "kind": string;
    "value": string;
    "options"?: string[] | null;
}

export interface SettingsGroup {
    "title": string;
    "fields": SettingField[] | null;
}

export interface ShellState {
    "appTitle": string;
    "appVersion": string;
    "themeMode": string;
    "currentPage": string;
    "topNav": NavItem[] | null;
    "bottomNav": NavItem[] | null;
    "dashboard": DashboardState;
    "runtimeGroups": SettingsGroup[] | null;
    "strategyRules": StrategyRule[] | null;
    "dimensionGroups": string[] | null;
    "reverseFillPlan": ReverseFillRow[] | null;
    "logLines": string[] | null;
    "communityItems": string[] | null;
    "aboutItems": PageMetric[] | null;
    "donateItems": PageMetric[] | null;
    "settingsGroups": SettingsGroup[] | null;
}

export interface StrategyRule {
    "condition": string;
    "action": string;
    "target": string;
}

export interface SurveyCoreState {
    "definition"?: surveycore$0.SurveyDefinition | null;
    "config"?: surveycore$0.RuntimeConfig | null;
    "result"?: surveycore$0.RunResult | null;
    "events"?: surveycore$0.Event[] | null;
}

export interface TestAIConnectionRequest {
    "config": surveycore$0.RuntimeConfig;
}

export interface TestCustomProxyAPIRequest {
    "url": string;
}
