// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as proxycore$0 from "../../../../../surveycontroller/proxycore/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as surveycore$0 from "../../../../../surveycontroller/surveycore/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as configio$0 from "../../../../../surveycontroller/surveycore/configio/models.js";

export interface AIConnectionTestState {
    "success": boolean;
    "message": string;
}

export enum AICredentialOperation {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    AICredentialKeep = "keep",
    AICredentialReplace = "replace",
    AICredentialClear = "clear",
};

export interface AICredentialUpdate {
    "operation": AICredentialOperation;
    "apiKey"?: string;
}

export interface AIProfileSettings {
    "mode": string;
    "provider": string;
    "baseURL"?: string;
    "apiProtocol": string;
    "model"?: string;
    "systemPrompt"?: string;
    "hasAPIKey": boolean;
}

export interface AppSettings {
    "schemaVersion": number;
    "configDirectory": string;
    "themeMode": string;
    "showNavigationText": boolean;
    "micaEnabled": boolean;
    "topmost": boolean;
    "askSaveOnClose": boolean;
    "preventSleepDuringRun": boolean;
    "taskResultNotification": boolean;
    "submissionReportTelemetry": boolean;
    "setupWizardVersion": number;
    "autoCheckUpdate": boolean;
    "autoSaveLogs": boolean;
    "autosaveLogCount": number;
    "aiProfile": AIProfileSettings;
}

export interface CheckTaskRequest {
    "config": configio$0.ConfigDocument;
    "aiProfile"?: AIProfileSettings | null;
}

export interface ConfigFileState {
    "path": string;
    "exists": boolean;
    "config"?: configio$0.ConfigDocument | null;
}

export interface CustomProxyAPITestState {
    "success": boolean;
    "message": string;
    "proxies": string[] | null;
}

export interface DecodeQRCodeRequest {
    "path": string;
    "dataUrl"?: string;
    "name"?: string;
}

export interface FixedProxyTestState {
    "success": boolean;
    "message": string;
    "address"?: string;
    "statusCode"?: number;
    "durationMs"?: number;
}

export interface LoadConfigRequest {
    "path": string;
}

export interface ParseSurveyRequest {
    "url": string;
}

export interface ProxyAreaCity {
    "code": string;
    "name": string;
}

export interface ProxyAreaOptionsState {
    "source": string;
    "hasAll": boolean;
    "provinces": ProxyAreaProvince[] | null;
}

export interface ProxyAreaProvince {
    "code": string;
    "name": string;
    "cities": ProxyAreaCity[] | null;
}

export interface ProxyRedeemState {
    "redeemed": boolean;
    "cardQuota": number;
    "cardQuotaLabel": string;
    "detail"?: string;
    "status": ProxyStatus;
}

export interface ProxyStatus {
    "available": number;
    "inUse": number;
    "userId": number;
    "userKnown": boolean;
    "poolRemainingIp": number;
    "poolRemainingKnown": boolean;
    "remainingQuota": string;
    "totalQuota": string;
    "quotaKnown": boolean;
    "randomIpEnabled": boolean;
    "source": string;
    "message": string;
    "quota": proxycore$0.QuotaSnapshot;
}

export interface QRCodeDecodeState {
    "path": string;
    "text": string;
}

export interface RedeemProxyCardRequest {
    "cardCode": string;
    "source"?: string;
}

export interface ReverseFillPreviewRequest {
    "path": string;
    "format": string;
    "startRow": number;
    "questions": surveycore$0.QuestionMeta[] | null;
}

export interface RunSurveyRequest {
    "config": configio$0.ConfigDocument;
}

export interface RunTaskEvent {
    "sequence": number;
    "event": surveycore$0.Event;
}

export interface RunTaskState {
    "runId"?: string;
    "status": RunTaskStatus;
    "pauseReason"?: string;
    "result"?: surveycore$0.RunResult | null;
    "events"?: RunTaskEvent[] | null;
    "nextSequence": number;
    "droppedEvents": number;
    "error"?: string;
    "startedAt"?: string;
    "endedAt"?: string;
}

export interface RunTaskStateRequest {
    "runId"?: string;
    "afterSequence"?: number;
}

export enum RunTaskStatus {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    RunTaskStatusIdle = "idle",
    RunTaskStatusRunning = "running",
    RunTaskStatusPaused = "paused",
    RunTaskStatusCanceling = "canceling",
    RunTaskStatusSucceeded = "succeeded",
    RunTaskStatusFailed = "failed",
    RunTaskStatusStopped = "stopped",
};

export interface SaveConfigRequest {
    "path": string;
    "config": configio$0.ConfigDocument;
}

export interface SaveSettingsRequest {
    "settings": AppSettings;
    "aiCredential": AICredentialUpdate;
}

export interface TaskCheckProblem {
    "code": string;
    "message": string;
    "step": string;
    "severity": string;
}

export interface TaskCheckState {
    "status": TaskCheckStatus;
    "problems": TaskCheckProblem[] | null;
}

export enum TaskCheckStatus {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    TaskCheckReady = "ready",
    TaskCheckWarning = "warning",
    TaskCheckBlocked = "blocked",
};

export interface TestAIConnectionRequest {
    "aiProfile": AIProfileSettings;
}

export interface TestCustomProxyAPIRequest {
    "url": string;
}

export interface TestFixedProxyRequest {
    "address": string;
    "targetUrl"?: string;
}
