// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as proxycore$0 from "../../../../../surveycontroller/proxycore/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as surveycore$0 from "../../../../../surveycontroller/surveycore/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as model$0 from "../../../../../surveycontroller/surveycore/internal/model/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as time$0 from "../../../../../time/models.js";

export class AIConnectionTestState {
    /**
     * Creates a new AIConnectionTestState instance.
     * @param {Partial<AIConnectionTestState>} [$$source = {}] - The source object to create the AIConnectionTestState.
     */
    constructor($$source = {}) {
        if (!("success" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["success"] = false;
        }
        if (!("message" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["message"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AIConnectionTestState instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {AIConnectionTestState}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new AIConnectionTestState(/** @type {Partial<AIConnectionTestState>} */($$parsedSource));
    }
}

export class AppSettings {
    /**
     * Creates a new AppSettings instance.
     * @param {Partial<AppSettings>} [$$source = {}] - The source object to create the AppSettings.
     */
    constructor($$source = {}) {
        if (!("configDirectory" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["configDirectory"] = "";
        }
        if (!("themeMode" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["themeMode"] = "";
        }
        if (!("showNavigationText" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["showNavigationText"] = false;
        }
        if (!("micaEnabled" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["micaEnabled"] = false;
        }
        if (!("topmost" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["topmost"] = false;
        }
        if (!("askSaveOnClose" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["askSaveOnClose"] = false;
        }
        if (!("preventSleepDuringRun" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["preventSleepDuringRun"] = false;
        }
        if (!("taskResultNotification" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["taskResultNotification"] = false;
        }
        if (!("submissionReportTelemetry" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["submissionReportTelemetry"] = false;
        }
        if (!("startupTutorialHintSeen" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["startupTutorialHintSeen"] = false;
        }
        if (!("randomIpBonusPlayed" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["randomIpBonusPlayed"] = false;
        }
        if (!("autoCheckUpdate" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["autoCheckUpdate"] = false;
        }
        if (!("autoSaveLogs" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["autoSaveLogs"] = false;
        }
        if (!("notifications" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["notifications"] = false;
        }
        if (!("autosaveLogCount" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["autosaveLogCount"] = 0;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {{ [_ in string]?: string } | undefined}
             */
            this["runtimeDefaults"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AppSettings instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {AppSettings}
     */
    static createFrom($$source = {}) {
        const $$createField15_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("runtimeDefaults" in $$parsedSource) {
            $$parsedSource["runtimeDefaults"] = $$createField15_0($$parsedSource["runtimeDefaults"]);
        }
        return new AppSettings(/** @type {Partial<AppSettings>} */($$parsedSource));
    }
}

export class ConfigFileState {
    /**
     * Creates a new ConfigFileState instance.
     * @param {Partial<ConfigFileState>} [$$source = {}] - The source object to create the ConfigFileState.
     */
    constructor($$source = {}) {
        if (!("path" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["path"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {surveycore$0.RuntimeConfig | null | undefined}
             */
            this["config"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ConfigFileState instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ConfigFileState}
     */
    static createFrom($$source = {}) {
        const $$createField1_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("config" in $$parsedSource) {
            $$parsedSource["config"] = $$createField1_0($$parsedSource["config"]);
        }
        return new ConfigFileState(/** @type {Partial<ConfigFileState>} */($$parsedSource));
    }
}

export class ContactRequest {
    /**
     * Creates a new ContactRequest instance.
     * @param {Partial<ContactRequest>} [$$source = {}] - The source object to create the ContactRequest.
     */
    constructor($$source = {}) {
        if (!("messageType" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["messageType"] = "";
        }
        if (!("issueTitle" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["issueTitle"] = "";
        }
        if (!("email" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["email"] = "";
        }
        if (!("message" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["message"] = "";
        }
        if (!("attachments" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["attachments"] = [];
        }
        if (!("autoAttachConfig" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["autoAttachConfig"] = false;
        }
        if (!("autoAttachLog" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["autoAttachLog"] = false;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {surveycore$0.RuntimeConfig | null | undefined}
             */
            this["config"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string[] | undefined}
             */
            this["logLines"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ContactRequest instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ContactRequest}
     */
    static createFrom($$source = {}) {
        const $$createField4_0 = $$createType3;
        const $$createField7_0 = $$createType2;
        const $$createField8_0 = $$createType3;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("attachments" in $$parsedSource) {
            $$parsedSource["attachments"] = $$createField4_0($$parsedSource["attachments"]);
        }
        if ("config" in $$parsedSource) {
            $$parsedSource["config"] = $$createField7_0($$parsedSource["config"]);
        }
        if ("logLines" in $$parsedSource) {
            $$parsedSource["logLines"] = $$createField8_0($$parsedSource["logLines"]);
        }
        return new ContactRequest(/** @type {Partial<ContactRequest>} */($$parsedSource));
    }
}

export class ContactState {
    /**
     * Creates a new ContactState instance.
     * @param {Partial<ContactState>} [$$source = {}] - The source object to create the ContactState.
     */
    constructor($$source = {}) {
        if (!("sent" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["sent"] = false;
        }
        if (!("message" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["message"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ContactState instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ContactState}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ContactState(/** @type {Partial<ContactState>} */($$parsedSource));
    }
}

export class ContactStatus {
    /**
     * Creates a new ContactStatus instance.
     * @param {Partial<ContactStatus>} [$$source = {}] - The source object to create the ContactStatus.
     */
    constructor($$source = {}) {
        if (!("text" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["text"] = "";
        }
        if (!("color" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["color"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ContactStatus instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ContactStatus}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ContactStatus(/** @type {Partial<ContactStatus>} */($$parsedSource));
    }
}

export class CustomProxyAPITestState {
    /**
     * Creates a new CustomProxyAPITestState instance.
     * @param {Partial<CustomProxyAPITestState>} [$$source = {}] - The source object to create the CustomProxyAPITestState.
     */
    constructor($$source = {}) {
        if (!("success" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["success"] = false;
        }
        if (!("message" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["message"] = "";
        }
        if (!("proxies" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["proxies"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CustomProxyAPITestState instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {CustomProxyAPITestState}
     */
    static createFrom($$source = {}) {
        const $$createField2_0 = $$createType3;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("proxies" in $$parsedSource) {
            $$parsedSource["proxies"] = $$createField2_0($$parsedSource["proxies"]);
        }
        return new CustomProxyAPITestState(/** @type {Partial<CustomProxyAPITestState>} */($$parsedSource));
    }
}

export class DashboardState {
    /**
     * Creates a new DashboardState instance.
     * @param {Partial<DashboardState>} [$$source = {}] - The source object to create the DashboardState.
     */
    constructor($$source = {}) {
        if (!("surveyTitle" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["surveyTitle"] = "";
        }
        if (!("surveyUrl" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["surveyUrl"] = "";
        }
        if (!("targetCount" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["targetCount"] = 0;
        }
        if (!("threadCount" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["threadCount"] = 0;
        }
        if (!("randomIpEnabled" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["randomIpEnabled"] = false;
        }
        if (!("randomIpQuota" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["randomIpQuota"] = 0;
        }
        if (!("randomIpQuotaLabel" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["randomIpQuotaLabel"] = "";
        }
        if (!("randomIpStatus" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["randomIpStatus"] = "";
        }
        if (!("randomIpStatusTone" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["randomIpStatusTone"] = "";
        }
        if (!("proxySource" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["proxySource"] = "";
        }
        if (!("questionCount" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["questionCount"] = 0;
        }
        if (!("progressCurrent" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["progressCurrent"] = 0;
        }
        if (!("progressTarget" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["progressTarget"] = 0;
        }
        if (!("progressPercent" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["progressPercent"] = 0;
        }
        if (!("statusText" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["statusText"] = "";
        }
        if (!("platformLabel" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["platformLabel"] = "";
        }
        if (!("metrics" in $$source)) {
            /**
             * @member
             * @type {PageMetric[]}
             */
            this["metrics"] = [];
        }
        if (!("quickActions" in $$source)) {
            /**
             * @member
             * @type {QuickAction[]}
             */
            this["quickActions"] = [];
        }
        if (!("questionRows" in $$source)) {
            /**
             * @member
             * @type {QuestionRow[]}
             */
            this["questionRows"] = [];
        }
        if (!("sessionRows" in $$source)) {
            /**
             * @member
             * @type {SessionRow[]}
             */
            this["sessionRows"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DashboardState instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {DashboardState}
     */
    static createFrom($$source = {}) {
        const $$createField16_0 = $$createType5;
        const $$createField17_0 = $$createType7;
        const $$createField18_0 = $$createType9;
        const $$createField19_0 = $$createType11;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("metrics" in $$parsedSource) {
            $$parsedSource["metrics"] = $$createField16_0($$parsedSource["metrics"]);
        }
        if ("quickActions" in $$parsedSource) {
            $$parsedSource["quickActions"] = $$createField17_0($$parsedSource["quickActions"]);
        }
        if ("questionRows" in $$parsedSource) {
            $$parsedSource["questionRows"] = $$createField18_0($$parsedSource["questionRows"]);
        }
        if ("sessionRows" in $$parsedSource) {
            $$parsedSource["sessionRows"] = $$createField19_0($$parsedSource["sessionRows"]);
        }
        return new DashboardState(/** @type {Partial<DashboardState>} */($$parsedSource));
    }
}

export class DecodeQRCodeRequest {
    /**
     * Creates a new DecodeQRCodeRequest instance.
     * @param {Partial<DecodeQRCodeRequest>} [$$source = {}] - The source object to create the DecodeQRCodeRequest.
     */
    constructor($$source = {}) {
        if (!("path" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["path"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["dataUrl"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["name"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DecodeQRCodeRequest instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {DecodeQRCodeRequest}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new DecodeQRCodeRequest(/** @type {Partial<DecodeQRCodeRequest>} */($$parsedSource));
    }
}

export class IPUsageRecord {
    /**
     * Creates a new IPUsageRecord instance.
     * @param {Partial<IPUsageRecord>} [$$source = {}] - The source object to create the IPUsageRecord.
     */
    constructor($$source = {}) {
        if (!("label" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["label"] = "";
        }
        if (!("total" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["total"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new IPUsageRecord instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {IPUsageRecord}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new IPUsageRecord(/** @type {Partial<IPUsageRecord>} */($$parsedSource));
    }
}

export class IPUsageSummary {
    /**
     * Creates a new IPUsageSummary instance.
     * @param {Partial<IPUsageSummary>} [$$source = {}] - The source object to create the IPUsageSummary.
     */
    constructor($$source = {}) {
        if (!("remainingQuota" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["remainingQuota"] = "";
        }
        if (!("totalQuota" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["totalQuota"] = "";
        }
        if (!("available" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["available"] = 0;
        }
        if (!("inUse" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["inUse"] = 0;
        }
        if (!("source" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["source"] = "";
        }
        if (!("message" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["message"] = "";
        }
        if (!("updatedAt" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["updatedAt"] = "";
        }
        if (!("records" in $$source)) {
            /**
             * @member
             * @type {IPUsageRecord[]}
             */
            this["records"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new IPUsageSummary instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {IPUsageSummary}
     */
    static createFrom($$source = {}) {
        const $$createField7_0 = $$createType13;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("records" in $$parsedSource) {
            $$parsedSource["records"] = $$createField7_0($$parsedSource["records"]);
        }
        return new IPUsageSummary(/** @type {Partial<IPUsageSummary>} */($$parsedSource));
    }
}

export class LoadConfigRequest {
    /**
     * Creates a new LoadConfigRequest instance.
     * @param {Partial<LoadConfigRequest>} [$$source = {}] - The source object to create the LoadConfigRequest.
     */
    constructor($$source = {}) {
        if (!("path" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["path"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new LoadConfigRequest instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {LoadConfigRequest}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new LoadConfigRequest(/** @type {Partial<LoadConfigRequest>} */($$parsedSource));
    }
}

export class NavItem {
    /**
     * Creates a new NavItem instance.
     * @param {Partial<NavItem>} [$$source = {}] - The source object to create the NavItem.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("label" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["label"] = "";
        }
        if (!("icon" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["icon"] = "";
        }
        if (!("section" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["section"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["badge"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {boolean | undefined}
             */
            this["selected"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new NavItem instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {NavItem}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new NavItem(/** @type {Partial<NavItem>} */($$parsedSource));
    }
}

export class PageMetric {
    /**
     * Creates a new PageMetric instance.
     * @param {Partial<PageMetric>} [$$source = {}] - The source object to create the PageMetric.
     */
    constructor($$source = {}) {
        if (!("label" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["label"] = "";
        }
        if (!("value" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["value"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["tone"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PageMetric instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {PageMetric}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new PageMetric(/** @type {Partial<PageMetric>} */($$parsedSource));
    }
}

export class ParseSurveyRequest {
    /**
     * Creates a new ParseSurveyRequest instance.
     * @param {Partial<ParseSurveyRequest>} [$$source = {}] - The source object to create the ParseSurveyRequest.
     */
    constructor($$source = {}) {
        if (!("url" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["url"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ParseSurveyRequest instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ParseSurveyRequest}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ParseSurveyRequest(/** @type {Partial<ParseSurveyRequest>} */($$parsedSource));
    }
}

export class ProxyAreaCity {
    /**
     * Creates a new ProxyAreaCity instance.
     * @param {Partial<ProxyAreaCity>} [$$source = {}] - The source object to create the ProxyAreaCity.
     */
    constructor($$source = {}) {
        if (!("code" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["code"] = "";
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ProxyAreaCity instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ProxyAreaCity}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ProxyAreaCity(/** @type {Partial<ProxyAreaCity>} */($$parsedSource));
    }
}

export class ProxyAreaOptionsState {
    /**
     * Creates a new ProxyAreaOptionsState instance.
     * @param {Partial<ProxyAreaOptionsState>} [$$source = {}] - The source object to create the ProxyAreaOptionsState.
     */
    constructor($$source = {}) {
        if (!("source" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["source"] = "";
        }
        if (!("hasAll" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["hasAll"] = false;
        }
        if (!("provinces" in $$source)) {
            /**
             * @member
             * @type {ProxyAreaProvince[]}
             */
            this["provinces"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ProxyAreaOptionsState instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ProxyAreaOptionsState}
     */
    static createFrom($$source = {}) {
        const $$createField2_0 = $$createType15;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("provinces" in $$parsedSource) {
            $$parsedSource["provinces"] = $$createField2_0($$parsedSource["provinces"]);
        }
        return new ProxyAreaOptionsState(/** @type {Partial<ProxyAreaOptionsState>} */($$parsedSource));
    }
}

export class ProxyAreaProvince {
    /**
     * Creates a new ProxyAreaProvince instance.
     * @param {Partial<ProxyAreaProvince>} [$$source = {}] - The source object to create the ProxyAreaProvince.
     */
    constructor($$source = {}) {
        if (!("code" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["code"] = "";
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("cities" in $$source)) {
            /**
             * @member
             * @type {ProxyAreaCity[]}
             */
            this["cities"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ProxyAreaProvince instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ProxyAreaProvince}
     */
    static createFrom($$source = {}) {
        const $$createField2_0 = $$createType17;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("cities" in $$parsedSource) {
            $$parsedSource["cities"] = $$createField2_0($$parsedSource["cities"]);
        }
        return new ProxyAreaProvince(/** @type {Partial<ProxyAreaProvince>} */($$parsedSource));
    }
}

export class ProxyRedeemState {
    /**
     * Creates a new ProxyRedeemState instance.
     * @param {Partial<ProxyRedeemState>} [$$source = {}] - The source object to create the ProxyRedeemState.
     */
    constructor($$source = {}) {
        if (!("redeemed" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["redeemed"] = false;
        }
        if (!("cardQuota" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["cardQuota"] = 0;
        }
        if (!("cardQuotaLabel" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["cardQuotaLabel"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["detail"] = undefined;
        }
        if (!("status" in $$source)) {
            /**
             * @member
             * @type {ProxyStatus}
             */
            this["status"] = (new ProxyStatus());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ProxyRedeemState instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ProxyRedeemState}
     */
    static createFrom($$source = {}) {
        const $$createField4_0 = $$createType18;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("status" in $$parsedSource) {
            $$parsedSource["status"] = $$createField4_0($$parsedSource["status"]);
        }
        return new ProxyRedeemState(/** @type {Partial<ProxyRedeemState>} */($$parsedSource));
    }
}

export class ProxyStatus {
    /**
     * Creates a new ProxyStatus instance.
     * @param {Partial<ProxyStatus>} [$$source = {}] - The source object to create the ProxyStatus.
     */
    constructor($$source = {}) {
        if (!("available" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["available"] = 0;
        }
        if (!("inUse" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["inUse"] = 0;
        }
        if (!("remainingQuota" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["remainingQuota"] = "";
        }
        if (!("totalQuota" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["totalQuota"] = "";
        }
        if (!("quotaKnown" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["quotaKnown"] = false;
        }
        if (!("randomIpEnabled" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["randomIpEnabled"] = false;
        }
        if (!("source" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["source"] = "";
        }
        if (!("message" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["message"] = "";
        }
        if (!("quota" in $$source)) {
            /**
             * @member
             * @type {proxycore$0.QuotaSnapshot}
             */
            this["quota"] = (new proxycore$0.QuotaSnapshot());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ProxyStatus instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ProxyStatus}
     */
    static createFrom($$source = {}) {
        const $$createField8_0 = $$createType19;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("quota" in $$parsedSource) {
            $$parsedSource["quota"] = $$createField8_0($$parsedSource["quota"]);
        }
        return new ProxyStatus(/** @type {Partial<ProxyStatus>} */($$parsedSource));
    }
}

export class QRCodeDecodeState {
    /**
     * Creates a new QRCodeDecodeState instance.
     * @param {Partial<QRCodeDecodeState>} [$$source = {}] - The source object to create the QRCodeDecodeState.
     */
    constructor($$source = {}) {
        if (!("path" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["path"] = "";
        }
        if (!("text" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["text"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new QRCodeDecodeState instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {QRCodeDecodeState}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new QRCodeDecodeState(/** @type {Partial<QRCodeDecodeState>} */($$parsedSource));
    }
}

export class QuestionRow {
    /**
     * Creates a new QuestionRow instance.
     * @param {Partial<QuestionRow>} [$$source = {}] - The source object to create the QuestionRow.
     */
    constructor($$source = {}) {
        if (!("index" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["index"] = 0;
        }
        if (!("type" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["type"] = "";
        }
        if (!("dimension" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["dimension"] = "";
        }
        if (!("strategy" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["strategy"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new QuestionRow instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {QuestionRow}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new QuestionRow(/** @type {Partial<QuestionRow>} */($$parsedSource));
    }
}

export class QuickAction {
    /**
     * Creates a new QuickAction instance.
     * @param {Partial<QuickAction>} [$$source = {}] - The source object to create the QuickAction.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("label" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["label"] = "";
        }
        if (!("icon" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["icon"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["emphasis"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new QuickAction instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {QuickAction}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new QuickAction(/** @type {Partial<QuickAction>} */($$parsedSource));
    }
}

export class RandomIPBonusState {
    /**
     * Creates a new RandomIPBonusState instance.
     * @param {Partial<RandomIPBonusState>} [$$source = {}] - The source object to create the RandomIPBonusState.
     */
    constructor($$source = {}) {
        if (!("claimed" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["claimed"] = false;
        }
        if (!("bonusQuota" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["bonusQuota"] = 0;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["detail"] = undefined;
        }
        if (!("playConfetti" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["playConfetti"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RandomIPBonusState instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {RandomIPBonusState}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new RandomIPBonusState(/** @type {Partial<RandomIPBonusState>} */($$parsedSource));
    }
}

export class RedeemProxyCardRequest {
    /**
     * Creates a new RedeemProxyCardRequest instance.
     * @param {Partial<RedeemProxyCardRequest>} [$$source = {}] - The source object to create the RedeemProxyCardRequest.
     */
    constructor($$source = {}) {
        if (!("cardCode" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["cardCode"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["source"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RedeemProxyCardRequest instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {RedeemProxyCardRequest}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new RedeemProxyCardRequest(/** @type {Partial<RedeemProxyCardRequest>} */($$parsedSource));
    }
}

export class ReverseFillPreviewRequest {
    /**
     * Creates a new ReverseFillPreviewRequest instance.
     * @param {Partial<ReverseFillPreviewRequest>} [$$source = {}] - The source object to create the ReverseFillPreviewRequest.
     */
    constructor($$source = {}) {
        if (!("path" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["path"] = "";
        }
        if (!("format" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["format"] = "";
        }
        if (!("startRow" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["startRow"] = 0;
        }
        if (!("questions" in $$source)) {
            /**
             * @member
             * @type {surveycore$0.QuestionMeta[]}
             */
            this["questions"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ReverseFillPreviewRequest instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ReverseFillPreviewRequest}
     */
    static createFrom($$source = {}) {
        const $$createField3_0 = $$createType21;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("questions" in $$parsedSource) {
            $$parsedSource["questions"] = $$createField3_0($$parsedSource["questions"]);
        }
        return new ReverseFillPreviewRequest(/** @type {Partial<ReverseFillPreviewRequest>} */($$parsedSource));
    }
}

export class ReverseFillRow {
    /**
     * Creates a new ReverseFillRow instance.
     * @param {Partial<ReverseFillRow>} [$$source = {}] - The source object to create the ReverseFillRow.
     */
    constructor($$source = {}) {
        if (!("question" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["question"] = "";
        }
        if (!("column" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["column"] = "";
        }
        if (!("state" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["state"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ReverseFillRow instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ReverseFillRow}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ReverseFillRow(/** @type {Partial<ReverseFillRow>} */($$parsedSource));
    }
}

export class RunSurveyRequest {
    /**
     * Creates a new RunSurveyRequest instance.
     * @param {Partial<RunSurveyRequest>} [$$source = {}] - The source object to create the RunSurveyRequest.
     */
    constructor($$source = {}) {
        if (!("config" in $$source)) {
            /**
             * @member
             * @type {surveycore$0.RuntimeConfig}
             */
            this["config"] = (new surveycore$0.RuntimeConfig());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RunSurveyRequest instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {RunSurveyRequest}
     */
    static createFrom($$source = {}) {
        const $$createField0_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("config" in $$parsedSource) {
            $$parsedSource["config"] = $$createField0_0($$parsedSource["config"]);
        }
        return new RunSurveyRequest(/** @type {Partial<RunSurveyRequest>} */($$parsedSource));
    }
}

export class RunTaskState {
    /**
     * Creates a new RunTaskState instance.
     * @param {Partial<RunTaskState>} [$$source = {}] - The source object to create the RunTaskState.
     */
    constructor($$source = {}) {
        if (!("running" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["running"] = false;
        }
        if (!("canceling" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["canceling"] = false;
        }
        if (!("paused" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["paused"] = false;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["pauseReason"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {surveycore$0.RunResult | null | undefined}
             */
            this["result"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {surveycore$0.Event[] | undefined}
             */
            this["events"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["error"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {time$0.Time | undefined}
             */
            this["startedAt"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {time$0.Time | undefined}
             */
            this["endedAt"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {surveycore$0.RuntimeConfig | null | undefined}
             */
            this["config"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RunTaskState instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {RunTaskState}
     */
    static createFrom($$source = {}) {
        const $$createField4_0 = $$createType23;
        const $$createField5_0 = $$createType25;
        const $$createField9_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("result" in $$parsedSource) {
            $$parsedSource["result"] = $$createField4_0($$parsedSource["result"]);
        }
        if ("events" in $$parsedSource) {
            $$parsedSource["events"] = $$createField5_0($$parsedSource["events"]);
        }
        if ("config" in $$parsedSource) {
            $$parsedSource["config"] = $$createField9_0($$parsedSource["config"]);
        }
        return new RunTaskState(/** @type {Partial<RunTaskState>} */($$parsedSource));
    }
}

export class SaveConfigRequest {
    /**
     * Creates a new SaveConfigRequest instance.
     * @param {Partial<SaveConfigRequest>} [$$source = {}] - The source object to create the SaveConfigRequest.
     */
    constructor($$source = {}) {
        if (!("path" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["path"] = "";
        }
        if (!("config" in $$source)) {
            /**
             * @member
             * @type {surveycore$0.RuntimeConfig}
             */
            this["config"] = (new surveycore$0.RuntimeConfig());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SaveConfigRequest instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {SaveConfigRequest}
     */
    static createFrom($$source = {}) {
        const $$createField1_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("config" in $$parsedSource) {
            $$parsedSource["config"] = $$createField1_0($$parsedSource["config"]);
        }
        return new SaveConfigRequest(/** @type {Partial<SaveConfigRequest>} */($$parsedSource));
    }
}

export class SaveSettingsRequest {
    /**
     * Creates a new SaveSettingsRequest instance.
     * @param {Partial<SaveSettingsRequest>} [$$source = {}] - The source object to create the SaveSettingsRequest.
     */
    constructor($$source = {}) {
        if (!("settings" in $$source)) {
            /**
             * @member
             * @type {AppSettings}
             */
            this["settings"] = (new AppSettings());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SaveSettingsRequest instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {SaveSettingsRequest}
     */
    static createFrom($$source = {}) {
        const $$createField0_0 = $$createType26;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("settings" in $$parsedSource) {
            $$parsedSource["settings"] = $$createField0_0($$parsedSource["settings"]);
        }
        return new SaveSettingsRequest(/** @type {Partial<SaveSettingsRequest>} */($$parsedSource));
    }
}

export class SessionRow {
    /**
     * Creates a new SessionRow instance.
     * @param {Partial<SessionRow>} [$$source = {}] - The source object to create the SessionRow.
     */
    constructor($$source = {}) {
        if (!("thread" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["thread"] = "";
        }
        if (!("status" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["status"] = "";
        }
        if (!("progress" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["progress"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SessionRow instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {SessionRow}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SessionRow(/** @type {Partial<SessionRow>} */($$parsedSource));
    }
}

export class SettingField {
    /**
     * Creates a new SettingField instance.
     * @param {Partial<SettingField>} [$$source = {}] - The source object to create the SettingField.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("label" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["label"] = "";
        }
        if (!("description" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["description"] = "";
        }
        if (!("kind" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["kind"] = "";
        }
        if (!("value" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["value"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string[] | undefined}
             */
            this["options"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SettingField instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {SettingField}
     */
    static createFrom($$source = {}) {
        const $$createField5_0 = $$createType3;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("options" in $$parsedSource) {
            $$parsedSource["options"] = $$createField5_0($$parsedSource["options"]);
        }
        return new SettingField(/** @type {Partial<SettingField>} */($$parsedSource));
    }
}

export class SettingsGroup {
    /**
     * Creates a new SettingsGroup instance.
     * @param {Partial<SettingsGroup>} [$$source = {}] - The source object to create the SettingsGroup.
     */
    constructor($$source = {}) {
        if (!("title" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["title"] = "";
        }
        if (!("fields" in $$source)) {
            /**
             * @member
             * @type {SettingField[]}
             */
            this["fields"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SettingsGroup instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {SettingsGroup}
     */
    static createFrom($$source = {}) {
        const $$createField1_0 = $$createType28;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("fields" in $$parsedSource) {
            $$parsedSource["fields"] = $$createField1_0($$parsedSource["fields"]);
        }
        return new SettingsGroup(/** @type {Partial<SettingsGroup>} */($$parsedSource));
    }
}

export class ShellState {
    /**
     * Creates a new ShellState instance.
     * @param {Partial<ShellState>} [$$source = {}] - The source object to create the ShellState.
     */
    constructor($$source = {}) {
        if (!("appTitle" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["appTitle"] = "";
        }
        if (!("appVersion" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["appVersion"] = "";
        }
        if (!("themeMode" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["themeMode"] = "";
        }
        if (!("currentPage" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["currentPage"] = "";
        }
        if (!("topNav" in $$source)) {
            /**
             * @member
             * @type {NavItem[]}
             */
            this["topNav"] = [];
        }
        if (!("bottomNav" in $$source)) {
            /**
             * @member
             * @type {NavItem[]}
             */
            this["bottomNav"] = [];
        }
        if (!("dashboard" in $$source)) {
            /**
             * @member
             * @type {DashboardState}
             */
            this["dashboard"] = (new DashboardState());
        }
        if (!("runtimeGroups" in $$source)) {
            /**
             * @member
             * @type {SettingsGroup[]}
             */
            this["runtimeGroups"] = [];
        }
        if (!("strategyRules" in $$source)) {
            /**
             * @member
             * @type {StrategyRule[]}
             */
            this["strategyRules"] = [];
        }
        if (!("dimensionGroups" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["dimensionGroups"] = [];
        }
        if (!("reverseFillPlan" in $$source)) {
            /**
             * @member
             * @type {ReverseFillRow[]}
             */
            this["reverseFillPlan"] = [];
        }
        if (!("logLines" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["logLines"] = [];
        }
        if (!("communityItems" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["communityItems"] = [];
        }
        if (!("aboutItems" in $$source)) {
            /**
             * @member
             * @type {PageMetric[]}
             */
            this["aboutItems"] = [];
        }
        if (!("donateItems" in $$source)) {
            /**
             * @member
             * @type {PageMetric[]}
             */
            this["donateItems"] = [];
        }
        if (!("ipUsageItems" in $$source)) {
            /**
             * @member
             * @type {PageMetric[]}
             */
            this["ipUsageItems"] = [];
        }
        if (!("settingsGroups" in $$source)) {
            /**
             * @member
             * @type {SettingsGroup[]}
             */
            this["settingsGroups"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ShellState instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ShellState}
     */
    static createFrom($$source = {}) {
        const $$createField4_0 = $$createType30;
        const $$createField5_0 = $$createType30;
        const $$createField6_0 = $$createType31;
        const $$createField7_0 = $$createType33;
        const $$createField8_0 = $$createType35;
        const $$createField9_0 = $$createType3;
        const $$createField10_0 = $$createType37;
        const $$createField11_0 = $$createType3;
        const $$createField12_0 = $$createType3;
        const $$createField13_0 = $$createType5;
        const $$createField14_0 = $$createType5;
        const $$createField15_0 = $$createType5;
        const $$createField16_0 = $$createType33;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("topNav" in $$parsedSource) {
            $$parsedSource["topNav"] = $$createField4_0($$parsedSource["topNav"]);
        }
        if ("bottomNav" in $$parsedSource) {
            $$parsedSource["bottomNav"] = $$createField5_0($$parsedSource["bottomNav"]);
        }
        if ("dashboard" in $$parsedSource) {
            $$parsedSource["dashboard"] = $$createField6_0($$parsedSource["dashboard"]);
        }
        if ("runtimeGroups" in $$parsedSource) {
            $$parsedSource["runtimeGroups"] = $$createField7_0($$parsedSource["runtimeGroups"]);
        }
        if ("strategyRules" in $$parsedSource) {
            $$parsedSource["strategyRules"] = $$createField8_0($$parsedSource["strategyRules"]);
        }
        if ("dimensionGroups" in $$parsedSource) {
            $$parsedSource["dimensionGroups"] = $$createField9_0($$parsedSource["dimensionGroups"]);
        }
        if ("reverseFillPlan" in $$parsedSource) {
            $$parsedSource["reverseFillPlan"] = $$createField10_0($$parsedSource["reverseFillPlan"]);
        }
        if ("logLines" in $$parsedSource) {
            $$parsedSource["logLines"] = $$createField11_0($$parsedSource["logLines"]);
        }
        if ("communityItems" in $$parsedSource) {
            $$parsedSource["communityItems"] = $$createField12_0($$parsedSource["communityItems"]);
        }
        if ("aboutItems" in $$parsedSource) {
            $$parsedSource["aboutItems"] = $$createField13_0($$parsedSource["aboutItems"]);
        }
        if ("donateItems" in $$parsedSource) {
            $$parsedSource["donateItems"] = $$createField14_0($$parsedSource["donateItems"]);
        }
        if ("ipUsageItems" in $$parsedSource) {
            $$parsedSource["ipUsageItems"] = $$createField15_0($$parsedSource["ipUsageItems"]);
        }
        if ("settingsGroups" in $$parsedSource) {
            $$parsedSource["settingsGroups"] = $$createField16_0($$parsedSource["settingsGroups"]);
        }
        return new ShellState(/** @type {Partial<ShellState>} */($$parsedSource));
    }
}

export class StartupTutorialHintState {
    /**
     * Creates a new StartupTutorialHintState instance.
     * @param {Partial<StartupTutorialHintState>} [$$source = {}] - The source object to create the StartupTutorialHintState.
     */
    constructor($$source = {}) {
        if (!("shouldShow" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["shouldShow"] = false;
        }
        if (!("docUrl" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["docUrl"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new StartupTutorialHintState instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {StartupTutorialHintState}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new StartupTutorialHintState(/** @type {Partial<StartupTutorialHintState>} */($$parsedSource));
    }
}

export class StrategyRule {
    /**
     * Creates a new StrategyRule instance.
     * @param {Partial<StrategyRule>} [$$source = {}] - The source object to create the StrategyRule.
     */
    constructor($$source = {}) {
        if (!("condition" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["condition"] = "";
        }
        if (!("action" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["action"] = "";
        }
        if (!("target" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["target"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new StrategyRule instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {StrategyRule}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new StrategyRule(/** @type {Partial<StrategyRule>} */($$parsedSource));
    }
}

export class SurveyCoreState {
    /**
     * Creates a new SurveyCoreState instance.
     * @param {Partial<SurveyCoreState>} [$$source = {}] - The source object to create the SurveyCoreState.
     */
    constructor($$source = {}) {
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {surveycore$0.SurveyDefinition | null | undefined}
             */
            this["definition"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {surveycore$0.RuntimeConfig | null | undefined}
             */
            this["config"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {surveycore$0.RunResult | null | undefined}
             */
            this["result"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {surveycore$0.Event[] | undefined}
             */
            this["events"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SurveyCoreState instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {SurveyCoreState}
     */
    static createFrom($$source = {}) {
        const $$createField0_0 = $$createType39;
        const $$createField1_0 = $$createType2;
        const $$createField2_0 = $$createType23;
        const $$createField3_0 = $$createType25;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("definition" in $$parsedSource) {
            $$parsedSource["definition"] = $$createField0_0($$parsedSource["definition"]);
        }
        if ("config" in $$parsedSource) {
            $$parsedSource["config"] = $$createField1_0($$parsedSource["config"]);
        }
        if ("result" in $$parsedSource) {
            $$parsedSource["result"] = $$createField2_0($$parsedSource["result"]);
        }
        if ("events" in $$parsedSource) {
            $$parsedSource["events"] = $$createField3_0($$parsedSource["events"]);
        }
        return new SurveyCoreState(/** @type {Partial<SurveyCoreState>} */($$parsedSource));
    }
}

export class TestAIConnectionRequest {
    /**
     * Creates a new TestAIConnectionRequest instance.
     * @param {Partial<TestAIConnectionRequest>} [$$source = {}] - The source object to create the TestAIConnectionRequest.
     */
    constructor($$source = {}) {
        if (!("config" in $$source)) {
            /**
             * @member
             * @type {surveycore$0.RuntimeConfig}
             */
            this["config"] = (new surveycore$0.RuntimeConfig());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TestAIConnectionRequest instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {TestAIConnectionRequest}
     */
    static createFrom($$source = {}) {
        const $$createField0_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("config" in $$parsedSource) {
            $$parsedSource["config"] = $$createField0_0($$parsedSource["config"]);
        }
        return new TestAIConnectionRequest(/** @type {Partial<TestAIConnectionRequest>} */($$parsedSource));
    }
}

export class TestCustomProxyAPIRequest {
    /**
     * Creates a new TestCustomProxyAPIRequest instance.
     * @param {Partial<TestCustomProxyAPIRequest>} [$$source = {}] - The source object to create the TestCustomProxyAPIRequest.
     */
    constructor($$source = {}) {
        if (!("url" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["url"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TestCustomProxyAPIRequest instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {TestCustomProxyAPIRequest}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new TestCustomProxyAPIRequest(/** @type {Partial<TestCustomProxyAPIRequest>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = $Create.Map($Create.Any, $Create.Any);
const $$createType1 = model$0.RuntimeConfig.createFrom;
const $$createType2 = $Create.Nullable($$createType1);
const $$createType3 = $Create.Array($Create.Any);
const $$createType4 = PageMetric.createFrom;
const $$createType5 = $Create.Array($$createType4);
const $$createType6 = QuickAction.createFrom;
const $$createType7 = $Create.Array($$createType6);
const $$createType8 = QuestionRow.createFrom;
const $$createType9 = $Create.Array($$createType8);
const $$createType10 = SessionRow.createFrom;
const $$createType11 = $Create.Array($$createType10);
const $$createType12 = IPUsageRecord.createFrom;
const $$createType13 = $Create.Array($$createType12);
const $$createType14 = ProxyAreaProvince.createFrom;
const $$createType15 = $Create.Array($$createType14);
const $$createType16 = ProxyAreaCity.createFrom;
const $$createType17 = $Create.Array($$createType16);
const $$createType18 = ProxyStatus.createFrom;
const $$createType19 = proxycore$0.QuotaSnapshot.createFrom;
const $$createType20 = model$0.QuestionMeta.createFrom;
const $$createType21 = $Create.Array($$createType20);
const $$createType22 = model$0.RunResult.createFrom;
const $$createType23 = $Create.Nullable($$createType22);
const $$createType24 = model$0.Event.createFrom;
const $$createType25 = $Create.Array($$createType24);
const $$createType26 = AppSettings.createFrom;
const $$createType27 = SettingField.createFrom;
const $$createType28 = $Create.Array($$createType27);
const $$createType29 = NavItem.createFrom;
const $$createType30 = $Create.Array($$createType29);
const $$createType31 = DashboardState.createFrom;
const $$createType32 = SettingsGroup.createFrom;
const $$createType33 = $Create.Array($$createType32);
const $$createType34 = StrategyRule.createFrom;
const $$createType35 = $Create.Array($$createType34);
const $$createType36 = ReverseFillRow.createFrom;
const $$createType37 = $Create.Array($$createType36);
const $$createType38 = model$0.SurveyDefinition.createFrom;
const $$createType39 = $Create.Nullable($$createType38);
