"""随机 IP / 代理能力聚合导出。"""
from __future__ import annotations

from wjx.network.proxy.source import (
    PROXY_SOURCE_BENEFIT,
    get_custom_proxy_api_override,
    get_default_proxy_area_code,
    get_effective_proxy_api_url,
    get_proxy_area_code,
    get_proxy_minute_by_answer_seconds,
    get_proxy_occupy_minute,
    get_proxy_required_seconds_by_answer_seconds,
    get_proxy_source,
    get_proxy_upstream,
    get_quota_cost_by_minute,
    has_custom_proxy_api_override,
    is_custom_proxy_api_active,
    is_custom_proxy_source,
    is_official_proxy_source,
    normalize_proxy_source,
    set_proxy_api_override,
    set_proxy_area_code,
    set_proxy_occupy_minute_by_answer_duration,
    set_proxy_source,
    source_supports_quota_session,
    source_uses_custom_api_override,
)
from wjx.network.proxy.pool import (
    get_proxy_required_ttl_seconds,
    proxy_lease_has_sufficient_ttl,
)
from wjx.network.proxy.provider import (
    AreaProxyQualityError,
    ProxyApiFatalError,
    format_status_payload,
    get_status,
    test_custom_proxy_api,
)
from wjx.network.proxy.quota import (
    get_random_ip_counter_snapshot_local,
    get_random_ip_limit,
    normalize_random_ip_enabled_value,
)
from wjx.network.proxy.settings import (
    ProxySettings,
    apply_custom_proxy_api,
    apply_proxy_area_code,
    apply_proxy_source_settings,
    get_proxy_settings,
)
from wjx.utils.app.config import PROXY_SOURCE_CUSTOM, PROXY_SOURCE_DEFAULT
from wjx.network.proxy.auth import format_quota_value

__all__ = [
    "AreaProxyQualityError",
    "ProxyApiFatalError",
    "PROXY_SOURCE_BENEFIT",
    "PROXY_SOURCE_CUSTOM",
    "PROXY_SOURCE_DEFAULT",
    "ProxySettings",
    "apply_custom_proxy_api",
    "apply_proxy_area_code",
    "apply_proxy_source_settings",
    "format_status_payload",
    "get_custom_proxy_api_override",
    "get_default_proxy_area_code",
    "get_effective_proxy_api_url",
    "get_proxy_area_code",
    "get_proxy_minute_by_answer_seconds",
    "get_proxy_occupy_minute",
    "get_proxy_settings",
    "get_proxy_upstream",
    "get_proxy_required_seconds_by_answer_seconds",
    "get_proxy_required_ttl_seconds",
    "get_proxy_source",
    "get_quota_cost_by_minute",
    "format_quota_value",
    "get_random_ip_counter_snapshot_local",
    "get_random_ip_limit",
    "get_status",
    "has_custom_proxy_api_override",
    "is_custom_proxy_source",
    "is_custom_proxy_api_active",
    "is_official_proxy_source",
    "normalize_proxy_source",
    "normalize_random_ip_enabled_value",
    "proxy_lease_has_sufficient_ttl",
    "set_proxy_api_override",
    "set_proxy_area_code",
    "set_proxy_occupy_minute_by_answer_duration",
    "set_proxy_source",
    "source_supports_quota_session",
    "source_uses_custom_api_override",
    "test_custom_proxy_api",
]
